Repository woowacourse-teams/2023-baton, pull requests merged in 2023-07, with the labels that each got.

#8 webpack 초기 환경 설정
  FE/.babelrc
  FE/.eslintrc
  FE/.gitignore
  FE/.prettierrc
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/index.tsx
  FE/src/public/index.html
  FE/tsconfig.json
  FE/webpack/webpack.common.js
  FE/webpack/webpack.dev.js
  FE/webpack/webpack.prod.js
Labels: ❤️ FE

#6 깃허브 액션 CI 워크플로 작성
  .github/workflows/continuous-integration.yml
Labels: 💙 BE, 🐳 infra

#17 MSW 설정
  FE/package-lock.json
  FE/package.json
  FE/public/mockServiceWorker.js
  FE/src/index.tsx
  FE/src/mocks/handlers.ts
  FE/src/mocks/worker.ts
  FE/webpack/webpack.common.js
Labels: ✨ feat, ❤️ FE

#20 Avartar, Tag, Button, Modal 컴포넌트 구현
  FE/src/assets/close-icon-red.svg
  FE/src/components/common/Avatar.tsx
  FE/src/components/common/Button.tsx
  FE/src/components/common/Modal.tsx
  FE/src/components/common/Tag.tsx
  FE/src/public/index.html
  FE/src/styles/GlobalStyles.ts
  FE/src/types/image.d.ts
  FE/tsconfig.json
  FE/webpack/webpack.common.js
Labels: ✨ feat, ❤️ FE

#23 React Router 설정
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/index.tsx
  FE/src/layout/Layout.tsx
  FE/src/pages/LoginPage.tsx
  FE/src/pages/MainPage.tsx
  FE/src/pages/RunnerPostCreatePage.tsx
  FE/src/pages/RunnerPostPage.tsx
  FE/src/router.tsx
Labels: ✨ feat, ❤️ FE

#27 msw, tsconfig, Avatar 공통 변경사항 반영
  FE/src/components/common/Avatar.tsx
  FE/src/index.tsx
  FE/tsconfig.json
Labels: ❤️ FE

#35 러너 게시글 수정 API 구현
  backend/baton/src/main/java/touch/baton/domain/common/vo/ChattingRoomCount.java
  backend/baton/src/main/java/touch/baton/domain/common/vo/Contents.java
  backend/baton/src/main/java/touch/baton/domain/common/vo/Title.java
  backend/baton/src/main/java/touch/baton/domain/common/vo/TotalRating.java
  backend/baton/src/main/java/touch/baton/domain/common/vo/WatchedCount.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/RunnerPost.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/dto/RunnerPostUpdateRequest.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/vo/Deadline.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/vo/PullRequestUrl.java
  backend/baton/src/main/java/touch/baton/domain/tag/RunnerPostTag.java
  backend/baton/src/main/java/touch/baton/domain/tag/RunnerPostTags.java
  backend/baton/src/main/java/touch/baton/domain/tag/Tag.java
  backend/baton/src/main/java/touch/baton/domain/tag/repository/RunnerPostTagRepository.java
  backend/baton/src/main/java/touch/baton/domain/tag/repository/TagRepository.java
  backend/baton/src/main/java/touch/baton/domain/tag/vo/TagCount.java
  backend/baton/src/main/java/touch/baton/domain/tag/vo/TagName.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/controller/RunnerPostControllerTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostData.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceUpdateTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/repository/TagRepositoryTest.java
Labels: ✨ feat, 💙 BE

#30 러너 게시글 등록 API 구현
  backend/baton/src/main/java/touch/baton/domain/common/vo/ChattingRoomCount.java
  backend/baton/src/main/java/touch/baton/domain/common/vo/Contents.java
  backend/baton/src/main/java/touch/baton/domain/common/vo/Title.java
  backend/baton/src/main/java/touch/baton/domain/common/vo/WatchedCount.java
  backend/baton/src/main/java/touch/baton/domain/runner/exception/RunnerException.java
  backend/baton/src/main/java/touch/baton/domain/runner/repository/RunnerRepository.java
  backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerService.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/RunnerPost.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/dto/RunnerPostCreateRequest.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/vo/Deadline.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/vo/PullRequestUrl.java
  backend/baton/src/main/java/touch/baton/domain/tag/RunnerPostTags.java
  backend/baton/src/main/java/touch/baton/domain/tag/Tag.java
  backend/baton/src/main/java/touch/baton/domain/tag/repository/TagRepository.java
  backend/baton/src/main/java/touch/baton/domain/tag/vo/TagCount.java
  backend/baton/src/main/java/touch/baton/domain/tag/vo/TagName.java
  backend/baton/src/test/java/touch/baton/domain/common/vo/ChattingRoomCountTest.java
  backend/baton/src/test/java/touch/baton/domain/common/vo/WatchedCountTest.java
  backend/baton/src/test/java/touch/baton/domain/runner/repository/RunnerRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/runner/service/RunnerServiceReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/RunnerPostTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/controller/RunnerPostControllerCreateTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerFixture.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceCreateTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/RunnerPostTagsTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/TagTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/repository/TagRepositoryTest.java
Labels: ✨ feat, 💙 BE

#31 러너 게시글 조회 페이지 구현
  FE/src/assets/chatting-icon.svg
  FE/src/assets/eye-icon.svg
  FE/src/components/PostTag.tsx
  FE/src/components/PostTagList.tsx
  FE/src/mocks/data/runnerPostDetails.json
  FE/src/mocks/handlers.ts
  FE/src/pages/RunnerPostPage.tsx
Labels: ✨ feat, ❤️ FE

#33 러너 게시물 생성 페이지 구현
  FE/src/components/InputBox.tsx
  FE/src/components/TagInput.tsx
  FE/src/components/Textarea.tsx
  FE/src/pages/RunnerPostCreatePage.tsx
Labels: ✨ feat, ❤️ FE

#34 메인 페이지 구현
  FE/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  FE/src/components/RunnerPost/RunnerPostList/RunnerPostList.tsx
  FE/src/mocks/data/runnerPostList.json
  FE/src/mocks/handlers.ts
  FE/src/pages/MainPage.tsx
  FE/src/types/RunnerPost.ts
Labels: ✨ feat, ❤️ FE

#28 러너 게시글 상세 조회 및 삭제 API 구현
  backend/baton/src/main/java/touch/baton/domain/common/exception/BusinessException.java
  backend/baton/src/main/java/touch/baton/domain/member/Member.java
  backend/baton/src/main/java/touch/baton/domain/member/vo/ImageUrl.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/ProfileResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerPostResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/exception/RunnerPostBusinessException.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/repository/RunnerPostRepository.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/main/java/touch/baton/domain/tag/Tag.java
  backend/baton/src/main/java/touch/baton/domain/tag/repository/RunnerPostTagRepository.java
  backend/baton/src/main/java/touch/baton/domain/tag/vo/TagCount.java
  backend/baton/src/test/java/touch/baton/assure/common/AssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/fixture/MemberFixture.java
  backend/baton/src/test/java/touch/baton/assure/fixture/RunnerFixture.java
  backend/baton/src/test/java/touch/baton/assure/fixture/RunnerPostFixture.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredDeleteTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredReadTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
  backend/baton/src/test/java/touch/baton/config/AssuredTestConfig.java
  backend/baton/src/test/java/touch/baton/config/RepositoryTestConfig.java
  backend/baton/src/test/java/touch/baton/config/ServiceTestConfig.java
  backend/baton/src/test/java/touch/baton/domain/member/MemberTest.java
  backend/baton/src/test/java/touch/baton/domain/member/vo/ImageUrlTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostRepositoryDeleteTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostRepositoryReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceCreateTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceDeleteTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceReadTest.java
  backend/baton/src/test/java/touch/baton/domain/supporter/SupporterTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/repository/RunnerPostTagRepositoryTest.java
Labels: ✨ feat, 💙 BE

#41 러너 게시글 수정 API 구현
  backend/baton/src/main/java/touch/baton/domain/common/vo/TotalRating.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/RunnerPost.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/dto/RunnerPostUpdateRequest.java
  backend/baton/src/main/java/touch/baton/domain/tag/RunnerPostTag.java
  backend/baton/src/main/java/touch/baton/domain/tag/RunnerPostTags.java
  backend/baton/src/main/java/touch/baton/domain/tag/Tag.java
  backend/baton/src/main/java/touch/baton/domain/tag/vo/TagCount.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/controller/RunnerPostControllerTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostData.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceUpdateTest.java
Labels: ✨ feat, 💙 BE

#32 러너 게시글 조회 API 구현
  backend/baton/src/main/java/touch/baton/domain/common/response/ProfileResponse.java
  backend/baton/src/main/java/touch/baton/domain/common/response/RunnerPostReadResponse.java
  backend/baton/src/main/java/touch/baton/domain/common/response/RunnerPostResponse.java
  backend/baton/src/main/java/touch/baton/domain/common/vo/ChattingCount.java
  backend/baton/src/main/java/touch/baton/domain/member/Member.java
  backend/baton/src/main/java/touch/baton/domain/member/vo/Company.java
  backend/baton/src/main/java/touch/baton/domain/member/vo/Email.java
  backend/baton/src/main/java/touch/baton/domain/member/vo/GithubUrl.java
  backend/baton/src/main/java/touch/baton/domain/member/vo/ImageUrl.java
  backend/baton/src/main/java/touch/baton/domain/member/vo/MemberName.java
  backend/baton/src/main/java/touch/baton/domain/member/vo/OauthId.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/RunnerPost.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerPostResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/repository/RunnerPostRepository.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/main/java/touch/baton/domain/supporter/vo/ReviewCount.java
  backend/baton/src/main/java/touch/baton/domain/supporter/vo/StarCount.java
  backend/baton/src/test/java/touch/baton/assure/fixture/RunnerPostFixture.java
  backend/baton/src/test/java/touch/baton/domain/common/vo/ChattingCountTest.java
  backend/baton/src/test/java/touch/baton/domain/member/MemberTest.java
  backend/baton/src/test/java/touch/baton/domain/runner/RunnerTest.java
  backend/baton/src/test/java/touch/baton/domain/runner/repository/RunnerRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/runner/service/RunnerServiceReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/RunnerPostTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/controller/RunnerPostControllerCreateTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/controller/read/RunnerPostControllerReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostData.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostRepositoryDeleteTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostRepositoryReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerFixture.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceCreateTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceDeleteTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceReadTest.java
  backend/baton/src/test/java/touch/baton/domain/supporter/SupporterTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/RunnerPostTagTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/RunnerPostTagsTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/repository/RunnerPostTagRepositoryTest.java
Labels: ✨ feat, 💙 BE

#42 구현한 페이지 라우터 연결
  FE/src/assets/logo-image.svg
  FE/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  FE/src/components/TagInput.tsx
  FE/src/hooks/usePageRouter.ts
  FE/src/layout/Header.tsx
  FE/src/pages/MainPage.tsx
  FE/src/pages/RunnerPostCreatePage.tsx
  FE/src/pages/RunnerPostPage.tsx
Labels: ✨ feat, ❤️ FE

#47 리뷰 요청 글 전체 조회 API 수정, Tag이름 조회 수정
  backend/baton/src/main/java/touch/baton/domain/common/response/RunnerPostResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/controller/read/RunnerPostControllerReadTest.java
Labels: 🐛 bug, 💙 BE

#51 러너 게시글 태그 중복 조회 오류 해결
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
Labels: 🐛 bug, 💙 BE

#55 러너 글 목록 조회 API 변경에 따른 MainPage 수정
  FE/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  FE/src/components/RunnerPost/RunnerPostList/RunnerPostList.tsx
  FE/src/mocks/data/runnerPostList.json
  FE/src/types/RunnerPost.ts
Labels: ✨ feat, ❤️ FE

#69 API 요청 Endpoint 변경
  FE/public/index.html
  FE/src/App.tsx
  FE/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  FE/src/components/RunnerPost/RunnerPostList/RunnerPostList.tsx
  FE/src/constants/index.ts
  FE/src/mocks/handlers.ts
  FE/src/pages/RunnerPostCreatePage.tsx
  FE/src/pages/RunnerPostPage.tsx
  FE/src/types/RunnerPost.ts
  FE/tsconfig.json
  FE/webpack/webpack.common.js
  FE/webpack/webpack.dev.js
Labels: ✨ feat, ❤️ FE

#71 절대 경로 재설정
  FE/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  FE/src/components/RunnerPost/RunnerPostList/RunnerPostList.tsx
  FE/src/components/common/Tag.tsx
  FE/src/layout/Header.tsx
  FE/src/pages/MainPage.tsx
  FE/src/pages/RunnerPostCreatePage.tsx
  FE/src/pages/RunnerPostPage.tsx
  FE/src/router.tsx
  FE/tsconfig.json
  FE/webpack/webpack.common.js
Labels: ❤️ FE

#73 불필요한 환경 변수 플러그인 제거
  FE/webpack/webpack.common.js
Labels: ❤️ FE

#74 테스트 코드를 위한 Fixture 생성 및 RunnerPost 테이블에 status 칼럼 추가
  backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/RunnerPost.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/vo/ReviewStatus.java
  backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
  backend/baton/src/test/java/touch/baton/assure/fixture/RunnerPostFixture.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/RunnerPostTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostData.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostRepositoryDeleteTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostRepositoryReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceReadTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/RunnerPostTagFixture.java
  backend/baton/src/test/java/touch/baton/domain/tag/RunnerPostTagTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/repository/RunnerPostTagRepositoryTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/MemberFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerPostFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerPostTagsFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/SupporterFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/TagFixture.java
  backend/baton/src/test/java/touch/baton/fixture/repository/MemberRepositoryFixture.java
  backend/baton/src/test/java/touch/baton/fixture/repository/RunnerPostRepositoryFixture.java
  backend/baton/src/test/java/touch/baton/fixture/repository/RunnerRepositoryFixture.java
  backend/baton/src/test/java/touch/baton/fixture/repository/SupporterRepositoryFixture.java
  backend/baton/src/test/java/touch/baton/fixture/repository/TagRepositoryFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/ChattingCountFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/CompanyFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/ContentsFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/DeadlineFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/EmailFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/GithubUrlFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/ImageUrlFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/MemberNameFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/OauthIdFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/PullRequestUrlFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/ReviewCountFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/StarCountFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/TagCountFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/TagNameFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/TitleFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/TotalRatingFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/WatchedCountFixture.java
Labels: 💙 BE, ♻️ refactor

#66 RunnerPostTag에 FK 제약 조건 이름 수정
  backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/RunnerPost.java
  backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
  backend/baton/src/main/java/touch/baton/domain/tag/RunnerPostTag.java
Labels: 💙 BE, ♻️ refactor

#78 나누어져있는 RunnerPostResponse 통합
  backend/baton/src/main/java/touch/baton/domain/common/response/ProfileResponse.java
  backend/baton/src/main/java/touch/baton/domain/common/response/RunnerPostReadResponse.java
  backend/baton/src/main/java/touch/baton/domain/common/response/RunnerPostResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/ProfileResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerPostReadResponses.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerPostResponse.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredReadTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
Labels: 💙 BE, ♻️ refactor

#88 Label 컴포넌트 구현
  FE/src/components/common/Label.tsx
Labels: ✨ feat, ❤️ FE

#90 서포터 선택 결과 페이지 구현
  FE/src/pages/CreationResultPage.tsx
  FE/src/router.tsx
Labels: ✨ feat, ❤️ FE

#91 메인 페이지 및 상세 게시글 리뷰 상태 라벨 추가
  FE/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  FE/src/constants/index.ts
  FE/src/mocks/data/runnerPostDetails.json
  FE/src/mocks/data/runnerPostList.json
  FE/src/pages/RunnerPostPage.tsx
  FE/src/types/RunnerPost.ts
Labels: ✨ feat, ❤️ FE

#93 서포터 목록 조회 API 구현 version-test
  backend/baton/src/main/java/touch/baton/domain/common/vo/Introduction.java
  backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
  backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
  backend/baton/src/main/java/touch/baton/domain/supporter/controller/SupporterController.java
  backend/baton/src/main/java/touch/baton/domain/supporter/controller/response/SupporterReadResponses.java
  backend/baton/src/main/java/touch/baton/domain/supporter/controller/response/SupporterResponse.java
  backend/baton/src/main/java/touch/baton/domain/supporter/service/SupporterService.java
Labels: ✨ feat, 💙 BE

#92 서포터 선택 시 확인 모달창 구현
  FE/src/components/ConfirmModal.tsx
Labels: ✨ feat, ❤️ FE

#96 서포터 목록 조회 API 에서 별점 제거
  backend/baton/src/main/java/touch/baton/domain/supporter/controller/response/SupporterResponse.java
Labels: 💙 BE, ♻️ refactor

#94 러너 리뷰 요청 게시글 생성 version-test
  backend/baton/src/main/java/touch/baton/domain/runnerpost/RunnerPost.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/dto/RunnerPostCreateRequest.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/dto/RunnerPostCreateTestRequest.java
  backend/baton/src/test/java/touch/baton/config/ServiceTestConfig.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceCreateTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceDeleteTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceUpdateTest.java
Labels: ✨ feat, 💙 BE

#104 Profile에 isOwner 삭제하고 RunnerPostResponse에 isOwner 추가
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/ProfileResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerPostResponse.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
Labels: 💙 BE, ♻️ refactor

#106 Docker Hub와 GitHub self hosted runner를 이용한 CD 설정
  .github/workflows/continuous-deploy.yml
  Dockerfile
Labels: 💙 BE, 🐳 infra

#111 CI를 위한 테스트 코드 작성
  FE/jest.config.js
  FE/package.json
  FE/src/__test__/MainPage.test.tsx
Labels: ❤️ FE

#113 CI설정 with GitHub Actions
  .github/workflow/frontend_ci.yml
  frontend/.babelrc
  frontend/.eslintrc
  frontend/.gitignore
  frontend/.prettierrc
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/mockServiceWorker.js
  frontend/src/App.tsx
  frontend/src/__test__/MainPage.test.tsx
  frontend/src/assets/chatting-icon.svg
  frontend/src/assets/close-icon-red.svg
  frontend/src/assets/eye-icon.svg
  frontend/src/assets/fonts/PretendardVariable.woff2
  frontend/src/assets/github-icon.svg
  frontend/src/assets/logo-image.svg
  frontend/src/components/ConfirmModal.tsx
  frontend/src/components/InputBox.tsx
  frontend/src/components/PostTag.tsx
  frontend/src/components/PostTagList.tsx
  frontend/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  frontend/src/components/RunnerPost/RunnerPostList/RunnerPostList.tsx
  frontend/src/components/SupporterSelect/SupporterSelectItem/SupporterSelectItem.tsx
  frontend/src/components/SupporterSelect/SupporterSelectList/SupporterSelectList.tsx
  frontend/src/components/TagInput.tsx
  frontend/src/components/Textarea.tsx
  frontend/src/components/common/Avatar.tsx
  frontend/src/components/common/Button.tsx
  frontend/src/components/common/Label.tsx
  frontend/src/components/common/Modal.tsx
  frontend/src/components/common/Tag.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/usePageRouter.ts
  frontend/src/index.tsx
  frontend/src/layout/Header.tsx
  frontend/src/layout/Layout.tsx
  frontend/src/mocks/data/runnerPostDetails.json
  frontend/src/mocks/data/runnerPostList.json
  frontend/src/mocks/data/supporterCardList.json
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/worker.ts
  frontend/src/pages/CreationResultPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/src/pages/RunnerPostPage.tsx
  frontend/src/pages/SupporterSelectPage.tsx
  frontend/src/router.tsx
  frontend/src/styles/GlobalStyles.ts
  frontend/src/styles/ResetStyle.ts
  frontend/src/types/RunnerPost.ts
  frontend/src/types/SupporterSelect.ts
  frontend/src/types/font.d.ts
  frontend/src/types/image.d.ts
  frontend/tsconfig.json
  frontend/webpack/webpack.common.js
  frontend/webpack/webpack.dev.js
  frontend/webpack/webpack.prod.js
Labels: ❤️ FE

#116 ConfirmModal 컴포넌트 테스트코드 작성
  .github/workflows/frontend_ci.yml
  frontend/src/__test__/MainPage.test.tsx
  frontend/src/__test__/components.test.tsx
Labels: ❤️ FE

#109 러너 게시글 상세 조회 API 구현 version-test
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerPostResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/SupporterResponseTestVersion.java
Labels: ✨ feat, 💙 BE

#110 Test Fixture 파라미터 타입 수정
  backend/baton/src/test/java/touch/baton/assure/fixture/RunnerFixture.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredDeleteTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredReadTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/MemberFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerPostFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/SupporterFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/TagFixture.java
Labels: 💙 BE, ♻️ refactor

#117 클라이언트 예외를 위한 Validator 추가
  backend/baton/src/main/java/touch/baton/domain/common/GlobalControllerAdvice.java
  backend/baton/src/main/java/touch/baton/domain/common/exception/ClientErrorCode.java
  backend/baton/src/main/java/touch/baton/domain/common/exception/ClientRequestException.java
  backend/baton/src/main/java/touch/baton/domain/common/exception/validator/NotNullValidator.java
  backend/baton/src/main/java/touch/baton/domain/common/exception/validator/ValidNotNull.java
  backend/baton/src/main/java/touch/baton/domain/common/response/ErrorResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/exception/validator/FutureValidator.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/exception/validator/MaxLengthValidator.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/exception/validator/ValidFuture.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/exception/validator/ValidMaxLength.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/dto/RunnerPostCreateRequest.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/dto/RunnerPostUpdateRequest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceUpdateTest.java
Labels: ✨ feat, 💙 BE

#120 CORS 설정 및 Profile을 RunnerProfile로 변경
  backend/baton/src/main/java/touch/baton/config/WebMvcConfig.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/ProfileResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerPostResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerProfileResponse.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/RunnerPostTest.java
Labels: ✨ feat, 💙 BE, ♻️ refactor

#124 로그인 페이지 구현
  frontend/src/layout/Header.tsx
  frontend/src/pages/LoginPage.tsx
Labels: ✨ feat, ❤️ FE

#127 String 으로 된 Date 값을 LocalDateTime 으로 변경하는 컨버터 구현
  backend/baton/src/main/java/touch/baton/config/converter/ConverterConfig.java
  backend/baton/src/main/java/touch/baton/config/converter/StringDateToLocalDateTimeConverter.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerPostResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/dto/RunnerPostCreateTestRequest.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/vo/Deadline.java
  backend/baton/src/test/java/touch/baton/config/converter/ConverterConfigTest.java
  backend/baton/src/test/java/touch/baton/config/converter/StringDateToLocalDateTimeConverterTest.java
Labels: ✨ feat, 💙 BE

#128 서포터 선택 목록 -> 글 생성할 때 띄우는 기능 구현
  frontend/src/components/InputBox.tsx
  frontend/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  frontend/src/components/RunnerPost/RunnerPostList/RunnerPostList.tsx
  frontend/src/components/SelectSupportModal.tsx
  frontend/src/components/SelectedSupporter.tsx
  frontend/src/components/SupporterSelect/SupporterSelectItem/SupporterSelectItem.tsx
  frontend/src/components/SupporterSelect/SupporterSelectList/SupporterSelectList.tsx
  frontend/src/components/TagInput.tsx
  frontend/src/components/Textarea.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/usePageRouter.ts
  frontend/src/mocks/data/supporterCardList.json
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/src/pages/SupporterSelectPage.tsx
  frontend/src/router.tsx
  frontend/src/types/runnerPost.ts
  frontend/webpack/webpack.dev.js
Labels: ✨ feat, ❤️ FE

#133 서버 api 엔드포인트 변경
  frontend/src/__test__/components.test.tsx
  frontend/src/components/ConfirmModal.tsx
  frontend/src/constants/index.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/RunnerPostDetailPage.tsx
Labels: ✨ feat, ❤️ FE

#130 API 문서 자동화를 위한 Restdocs 설정
  backend/baton/build.gradle
  backend/baton/src/test/java/touch/baton/config/AssuredTestConfig.java
  backend/baton/src/test/java/touch/baton/config/RestdocsConfig.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadApiTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerPostFixture.java
Labels: ✨ feat, 💙 BE

#137 사용하지 않는 기능 숨기기
  frontend/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  frontend/src/components/common/Label.tsx
  frontend/src/layout/Header.tsx
  frontend/src/layout/Layout.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/RunnerPostDetailPage.tsx
Labels: ✨ feat, ❤️ FE

#139 secret 파일 pull
  .github/workflows/dev-be-ci-cd-push.yml
Labels: 🐛 bug, 💙 BE

#151 서포터 기술 태그 table 추가
  backend/baton/src/main/java/touch/baton/domain/common/vo/TagName.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
  backend/baton/src/main/java/touch/baton/domain/tag/Tag.java
  backend/baton/src/main/java/touch/baton/domain/tag/repository/TagRepository.java
  backend/baton/src/main/java/touch/baton/domain/technicaltag/SupporterTechnicalTag.java
  backend/baton/src/main/java/touch/baton/domain/technicaltag/SupporterTechnicalTags.java
  backend/baton/src/main/java/touch/baton/domain/technicaltag/TechnicalTag.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/RunnerPostTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/controller/read/RunnerPostControllerReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostData.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceDeleteTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceReadTest.java
  backend/baton/src/test/java/touch/baton/domain/supporter/SupporterTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/RunnerPostTagTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/TagTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/repository/RunnerPostTagRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/repository/TagRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/vo/TagNameTest.java
  backend/baton/src/test/java/touch/baton/domain/technicaltag/SupporterTechnicalTagTest.java
  backend/baton/src/test/java/touch/baton/domain/technicaltag/TechnicalTagTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerPostFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerPostTagFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/SupporterFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/SupporterTechnicalTagFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/SupporterTechnicalTagsFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/TagFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/TechnicalTagFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/TagNameFixture.java
Labels: ✨ feat, 💙 BE

#153 webpack prod publicPath 재설정
  frontend/webpack/webpack.prod.js
Labels: ❤️ FE, 🔧 fix

#155 프론트엔드 배포 작업
  frontend/webpack/webpack.prod.js
Labels: ❤️ FE, 🚀 deploy

#158 fix: docker network 설정
  .github/workflows/dev-be-ci-cd-push.yml
Labels: 💙 BE, 🚀 deploy, 🐳 infra, 🔧 fix

#160 cd 파일 재설정
  .github/workflows/deploy-all-ci-cd-push.yml
Labels: 💙 BE, 🚀 deploy

#161 백엔드 배포 작업
  .github/workflows/deploy-all-ci-cd-push.yml
Labels: 💙 BE, 🚀 deploy
