Repository woowacourse-teams/2023-baton, pull requests merged in 2023-08, with the labels that each got.

#162 서포터 전체 조회 기술 태그 목록 추가 version-test
  backend/baton/src/main/java/touch/baton/domain/supporter/controller/response/SupporterResponse.java
  backend/baton/src/test/java/touch/baton/domain/supporter/SupporterTest.java
Labels: ✨ feat, 💙 BE

#172 테스트 코드 Fixture 통일
  backend/baton/src/test/java/touch/baton/assure/fixture/MemberFixture.java
  backend/baton/src/test/java/touch/baton/assure/fixture/RunnerFixture.java
  backend/baton/src/test/java/touch/baton/assure/fixture/RunnerPostFixture.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredDeleteTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runner/repository/RunnerRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostData.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/read/RunnerPostRepositoryReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerFixture.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceCreateTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceUpdateTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/repository/TagRepositoryTest.java
Labels: 💙 BE, ♻️ refactor

#177 domain exception이 server exception을 상속받도록 수정
  backend/baton/src/main/java/touch/baton/domain/common/GlobalControllerAdvice.java
  backend/baton/src/main/java/touch/baton/domain/common/exception/BaseException.java
  backend/baton/src/main/java/touch/baton/domain/common/exception/BusinessException.java
  backend/baton/src/main/java/touch/baton/domain/common/exception/ClientErrorCode.java
  backend/baton/src/main/java/touch/baton/domain/common/exception/ClientRequestException.java
  backend/baton/src/main/java/touch/baton/domain/common/exception/DomainException.java
  backend/baton/src/main/java/touch/baton/domain/common/exception/ErrorCode.java
  backend/baton/src/main/java/touch/baton/domain/common/exception/ServerErrorCode.java
  backend/baton/src/main/java/touch/baton/domain/common/response/ErrorResponse.java
  backend/baton/src/main/java/touch/baton/domain/common/vo/Contents.java
  backend/baton/src/main/java/touch/baton/domain/common/vo/TagName.java
  backend/baton/src/main/java/touch/baton/domain/common/vo/Title.java
  backend/baton/src/main/java/touch/baton/domain/member/Member.java
  backend/baton/src/main/java/touch/baton/domain/member/exception/MemberBusinessException.java
  backend/baton/src/main/java/touch/baton/domain/member/exception/MemberDomainException.java
  backend/baton/src/main/java/touch/baton/domain/member/exception/OldMemberException.java
  backend/baton/src/main/java/touch/baton/domain/member/vo/Company.java
  backend/baton/src/main/java/touch/baton/domain/member/vo/Email.java
  backend/baton/src/main/java/touch/baton/domain/member/vo/GithubUrl.java
  backend/baton/src/main/java/touch/baton/domain/member/vo/ImageUrl.java
  backend/baton/src/main/java/touch/baton/domain/member/vo/MemberName.java
  backend/baton/src/main/java/touch/baton/domain/member/vo/OauthId.java
  backend/baton/src/main/java/touch/baton/domain/runner/exception/RunnerBusinessException.java
  backend/baton/src/main/java/touch/baton/domain/runner/exception/RunnerDomainException.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/exception/RunnerPostBusinessException.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/exception/RunnerPostDomainException.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/vo/Deadline.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/vo/PullRequestUrl.java
  backend/baton/src/main/java/touch/baton/domain/supporter/exception/SupporterBusinessException.java
  backend/baton/src/main/java/touch/baton/domain/supporter/exception/SupporterDomainException.java
  backend/baton/src/main/java/touch/baton/domain/tag/exception/TagBusinessException.java
  backend/baton/src/main/java/touch/baton/domain/tag/exception/TagDomainException.java
  backend/baton/src/test/java/touch/baton/domain/member/MemberTest.java
Labels: 💙 BE, ♻️ refactor

#182 게시물 상세 조회 페이지 디자인 수정
  frontend/src/components/common/Button.tsx
  frontend/src/pages/CreationResultPage.tsx
  frontend/src/pages/RunnerPostDetailPage.tsx
Labels: ❤️ FE, 💄 design

#185 마이페이지 구현
  frontend/src/components/ListFilter.tsx
  frontend/src/components/Profile/ProfileRunnerPostItem/ProfileRunnerPostItem.tsx
  frontend/src/mocks/data/runnerProfile.json
  frontend/src/mocks/handlers.ts
  frontend/src/pages/MyPage.tsx
  frontend/src/router.tsx
  frontend/src/types/profile.ts
  frontend/src/types/select.ts
Labels: ✨ feat, ❤️ FE

#181 서포터 선택 상세정보 개발언어 추가, 분야별 필터링 기능 구현
  frontend/src/assets/technicalLabelIcon.tsx
  frontend/src/components/SelectSupportModal.tsx
  frontend/src/components/SelectedSupporter.tsx
  frontend/src/components/SupporterSelect/SupporterSelectItem/SupporterSelectItem.tsx
  frontend/src/components/SupporterSelect/SupporterSelectList/SupporterSelectList.tsx
  frontend/src/components/TechLabel.tsx
  frontend/src/mocks/data/supporterCardList.json
  frontend/src/types/supporterCard.ts
Labels: ✨ feat, ❤️ FE

#193 Oauth API prefix 수정 및 깃허브 소셜 로그인 Http Method 수정
  backend/baton/src/main/java/touch/baton/domain/oauth/controller/OauthController.java
  backend/baton/src/test/java/touch/baton/document/oauth/github/GithubOauthApiTest.java
Labels: 🐛 bug, 💙 BE

#186 서포터 피드백 등록 API 구현
  backend/baton/src/main/java/touch/baton/domain/common/exception/ClientErrorCode.java
  backend/baton/src/main/java/touch/baton/domain/feedback/SupporterFeedback.java
  backend/baton/src/main/java/touch/baton/domain/feedback/controller/FeedbackController.java
  backend/baton/src/main/java/touch/baton/domain/feedback/exception/FeedbackBusinessException.java
  backend/baton/src/main/java/touch/baton/domain/feedback/exception/SupporterFeedbackException.java
  backend/baton/src/main/java/touch/baton/domain/feedback/repository/SupporterFeedbackRepository.java
  backend/baton/src/main/java/touch/baton/domain/feedback/service/FeedbackService.java
  backend/baton/src/main/java/touch/baton/domain/feedback/service/SupporterFeedBackCreateRequest.java
  backend/baton/src/main/java/touch/baton/domain/feedback/vo/Description.java
  backend/baton/src/main/java/touch/baton/domain/feedback/vo/ReviewType.java
  backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/RunnerPost.java
  backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
  backend/baton/src/test/java/touch/baton/assure/common/AssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/common/HttpStatusAndLocationHeader.java
  backend/baton/src/test/java/touch/baton/assure/feedback/SupporterFeedbackAssuredCreateTest.java
  backend/baton/src/test/java/touch/baton/assure/feedback/SupporterFeedbackAssuredSupport.java
  backend/baton/src/test/java/touch/baton/config/AssuredTestConfig.java
  backend/baton/src/test/java/touch/baton/config/ServiceTestConfig.java
  backend/baton/src/test/java/touch/baton/domain/common/vo/DescriptionTest.java
  backend/baton/src/test/java/touch/baton/domain/feedback/service/FeedbackServiceTest.java
  backend/baton/src/test/java/touch/baton/domain/supporter/SupporterFeedbackTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerPostFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/SupporterFeedbackFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/SupporterFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/DescriptionFixture.java
Labels: ✨ feat, 💙 BE

#184 모든 도메인 객체 exception Notnull method 제거
  backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
  backend/baton/src/main/java/touch/baton/domain/runner/exception/OldRunnerException.java
  backend/baton/src/main/java/touch/baton/domain/runner/exception/RunnerDomainException.java
  backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerService.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/RunnerPost.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/exception/OldRunnerPostBusinessException.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/exception/OldRunnerPostException.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
  backend/baton/src/main/java/touch/baton/domain/supporter/exception/OldSupporterException.java
  backend/baton/src/main/java/touch/baton/domain/tag/RunnerPostTag.java
  backend/baton/src/main/java/touch/baton/domain/tag/Tag.java
  backend/baton/src/main/java/touch/baton/domain/tag/exception/OldTagException.java
  backend/baton/src/main/java/touch/baton/domain/tag/exception/RunnerPostTagDomainException.java
  backend/baton/src/main/java/touch/baton/domain/tag/exception/SupporterTechnicalTagDomainException.java
  backend/baton/src/main/java/touch/baton/domain/tag/exception/TechnicalTagDomainException.java
  backend/baton/src/main/java/touch/baton/domain/technicaltag/SupporterTechnicalTag.java
  backend/baton/src/main/java/touch/baton/domain/technicaltag/TechnicalTag.java
  backend/baton/src/test/java/touch/baton/domain/runner/RunnerTest.java
  backend/baton/src/test/java/touch/baton/domain/runner/service/RunnerServiceReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/RunnerPostTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceDeleteTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceReadTest.java
  backend/baton/src/test/java/touch/baton/domain/supporter/SupporterTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/RunnerPostTagTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/TagTest.java
  backend/baton/src/test/java/touch/baton/domain/technicaltag/SupporterTechnicalTagTest.java
  backend/baton/src/test/java/touch/baton/domain/technicaltag/TechnicalTagTest.java
Labels: 💙 BE, ♻️ refactor

#183 러너 본인 프로필 조회 기능 구현
  backend/baton/src/main/java/touch/baton/domain/oauth/controller/OauthController.java
  backend/baton/src/main/java/touch/baton/domain/runner/controller/RunnerProfileController.java
  backend/baton/src/main/java/touch/baton/domain/runner/controller/response/RunnerMyProfileResponse.java
  backend/baton/src/main/java/touch/baton/domain/runner/controller/response/RunnerResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerPostResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/repository/RunnerPostRepository.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/test/java/touch/baton/assure/common/AssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/feedback/SupporterFeedbackAssuredCreateTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredDeleteTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredReadTest.java
  backend/baton/src/test/java/touch/baton/controller/runner/RunnerAssuredSupport.java
  backend/baton/src/test/java/touch/baton/controller/runner/RunnerProfileAssuredReadTest.java
  backend/baton/src/test/java/touch/baton/document/profile/runner/read/RunnerProfileReadApiTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostRepositoryReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/read/RunnerPostRepositoryReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceReadTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/IntroductionFixture.java
Labels: ✨ feat, 💙 BE

#198 웹 표준 및 웹 접근성 준수
  frontend/src/components/InputBox.tsx
  frontend/src/components/SelectSupportModal.tsx
  frontend/src/components/SupporterSelect/SupporterSelectItem/SupporterSelectItem.tsx
  frontend/src/components/common/Avatar.tsx
  frontend/src/components/common/Button.tsx
  frontend/src/components/common/Modal.tsx
  frontend/src/layout/Header.tsx
  frontend/src/layout/Layout.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/src/pages/RunnerPostDetailPage.tsx
Labels: ✨ feat, ❤️ FE, ♻️ refactor

#202 모든 API 인증 기능 추가
  backend/baton/src/main/java/touch/baton/domain/feedback/controller/FeedbackController.java
  backend/baton/src/main/java/touch/baton/domain/oauth/controller/resolver/AuthRunnerPrincipal.java
  backend/baton/src/main/java/touch/baton/domain/oauth/controller/resolver/AuthRunnerPrincipalArgumentResolver.java
  backend/baton/src/main/java/touch/baton/domain/oauth/controller/resolver/AuthSupporterPrincipal.java
  backend/baton/src/main/java/touch/baton/domain/oauth/controller/resolver/AuthSupporterPrincipalArgumentResolver.java
  backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerService.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerPostResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/main/java/touch/baton/domain/supporter/controller/response/SupporterResponse.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredDeleteTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredReadTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadApiTest.java
  backend/baton/src/test/java/touch/baton/domain/runner/service/RunnerServiceReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/controller/RunnerPostControllerCreateTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceDeleteTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceUpdateTest.java
  backend/baton/src/test/java/touch/baton/domain/supporter/SupporterTest.java
Labels: 💙 BE, ♻️ refactor

#200 서포터 선택 필터 기능 useEffect dependency 수정
  frontend/src/components/SupporterSelect/SupporterSelectItem/SupporterSelectItem.tsx
  frontend/src/components/SupporterSelect/SupporterSelectList/SupporterSelectList.tsx
Labels: ❤️ FE, 🔧 fix

#206 클라이언트 에러 HttpStatus 수정
  backend/baton/src/main/java/touch/baton/domain/common/exception/ClientErrorCode.java
Labels: 💙 BE, ♻️ refactor

#203 깃허브 소셜 로그인 기능 구현
  frontend/src/App.tsx
  frontend/src/components/ListFilter.tsx
  frontend/src/components/Profile/ProfileRunnerPostItem/ProfileRunnerPostItem.tsx
  frontend/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  frontend/src/components/common/Avatar.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/usePageRouter.ts
  frontend/src/hooks/useToken.ts
  frontend/src/layout/Header.tsx
  frontend/src/pages/GithubCallbackPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/src/pages/RunnerPostDetailPage.tsx
  frontend/src/router.tsx
Labels: ✨ feat, ❤️ FE

#215 [hotfix] 프론트엔드 엔드포인트 변경 후 재배포
  frontend/src/constants/index.ts
Labels: ❤️ FE, 🚀 deploy, 🔧 fix

#225 헤더 프로필 이름 렌더링 및 삭제 완료 후 메인페이지로 이동하는 기능 구현
  frontend/src/layout/Header.tsx
  frontend/src/pages/RunnerPostDetailPage.tsx
Labels: ✨ feat, ❤️ FE, 🔧 fix

#227 전체 조회 쿼리 날짜 역순으로 정렬
  backend/baton/src/main/java/touch/baton/domain/runnerpost/repository/RunnerPostRepository.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/read/RunnerPostRepositoryReadTest.java
Labels: 💙 BE, 🔧 fix

#230 러너 게시글 상세 조회 시 조회수가 증가하도록 변경
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceReadTest.java
Labels: 💙 BE, ♻️ refactor

#232 hotfix
  frontend/src/pages/RunnerPostDetailPage.tsx
Labels: ❤️ FE, 🔧 fix

#257 서포터 선택기능 제거
  frontend/src/mocks/handlers.ts
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/src/types/runnerPost.ts
Labels: ❤️ FE

#258 로그아웃시 기능 사용 못하도록 수정
  frontend/src/layout/Header.tsx
Labels: 🐛 bug, ❤️ FE

#259 스토리북 구현
  frontend/.storybook/main.ts
  frontend/.storybook/preview-body.html
  frontend/.storybook/preview.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/__test__/components.test.tsx
  frontend/src/components/ConfirmModal/ConfirmModal.tsx
  frontend/src/components/InputBox/InputBox.tsx
  frontend/src/components/ListFilter/ListFilter.tsx
  frontend/src/components/PostTag/PostTag.tsx
  frontend/src/components/PostTagList/PostTagList.tsx
  frontend/src/components/Profile/ProfileRunnerPostItem/ProfileRunnerPostItem.tsx
  frontend/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  frontend/src/components/SelectSupportModal/SelectSupportModal.tsx
  frontend/src/components/SelectedSupporter/SelectedSupporter.tsx
  frontend/src/components/SupporterSelect/SupporterSelectItem/SupporterSelectItem.tsx
  frontend/src/components/TagInput/TagInput.tsx
  frontend/src/components/TechLabel/TechLabel.tsx
  frontend/src/components/Textarea/Textarea.tsx
  frontend/src/components/common/Avatar/Avatar.stories.ts
  frontend/src/components/common/Avatar/Avatar.tsx
  frontend/src/components/common/Button/Button.stories.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/Label/Label.stories.ts
  frontend/src/components/common/Label/Label.tsx
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/Tag/Tag.stories.ts
  frontend/src/components/common/Tag/Tag.tsx
  frontend/src/layout/Header.tsx
  frontend/src/pages/CreationResultPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/src/pages/RunnerPostDetailPage.tsx
Labels: ❤️ FE

#261 프론트엔드 CD 설정
  .github/workflows/frontend_cd.yml
Labels: ❤️ FE, 🐳 infra

#263 프론트엔드 CD 테스트 (2)
  .github/workflows/frontend_cd.yml
Labels: ❤️ FE, 🚀 deploy, 🐳 infra

#267 프론트엔드 CD 재설정
  .github/workflows/frontend_cd.yml
Labels: ❤️ FE, 🚀 deploy, 🐳 infra

#271 Auth ArgumentResolver 익명 null 반환 변경
  backend/baton/src/main/java/touch/baton/domain/oauth/controller/resolver/AuthRunnerPrincipal.java
  backend/baton/src/main/java/touch/baton/domain/oauth/controller/resolver/AuthRunnerPrincipalArgumentResolver.java
  backend/baton/src/main/java/touch/baton/domain/oauth/controller/resolver/AuthSupporterPrincipal.java
  backend/baton/src/main/java/touch/baton/domain/oauth/controller/resolver/AuthSupporterPrincipalArgumentResolver.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
Labels: 💙 BE, ♻️ refactor

#282 백엔드 CI/CD 스크립트 수정
  .github/workflows/deploy-be-ci-cd-push.yml
  .github/workflows/deploy-be-ci-pr.yml
  .github/workflows/dev-be-ci-cd-push.yml
  .github/workflows/dev-be-ci-pr.yml
Labels: 💙 BE, ♻️ refactor

#285 CI/CD container 타임존 설정
  .github/workflows/deploy-be-ci-cd-push.yml
  .github/workflows/dev-be-ci-cd-push.yml
  backend/baton/Dockerfile-deploy
  backend/baton/Dockerfile-dev
Labels: 💙 BE, 🔧 fix

#287 TagCount 삭제
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/main/java/touch/baton/domain/tag/Tag.java
  backend/baton/src/main/java/touch/baton/domain/tag/vo/TagCount.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadApiTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceDeleteTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceReadTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/RunnerPostTagTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/TagTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/repository/RunnerPostTagRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/repository/TagRepositoryTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/TagFixture.java
  backend/baton/src/test/java/touch/baton/fixture/vo/TagCountFixture.java
Labels: 💙 BE, ♻️ refactor

#294 프론트 개발 서버용 CD 설정
  .github/workflows/frontend_cd.yml
  frontend/public/index.html
  frontend/src/constants/index.ts
Labels: ✨ feat, ❤️ FE, 🐳 infra, 🔧 fix

#297 Dockerfile 오류 해결
  backend/baton/Dockerfile-deploy
  backend/baton/Dockerfile-dev
Labels: 🐛 bug, 💙 BE

#299 프론트 개발 서버용 CD 설정
  .github/workflows/frontend_dev_cd.yml
  frontend/src/constants/index.ts
Labels: ❤️ FE, 🐳 infra, 🔧 fix

#298 서포터 프로필 조회 API 구현
  backend/baton/src/main/java/touch/baton/domain/supporter/controller/SupporterProfileController.java
  backend/baton/src/main/java/touch/baton/domain/supporter/controller/response/SupporterResponse.java
  backend/baton/src/main/java/touch/baton/domain/supporter/repository/SupporterRepository.java
  backend/baton/src/main/java/touch/baton/domain/supporter/service/SupporterService.java
  backend/baton/src/test/java/touch/baton/assure/common/AssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredReadTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterProfileAssuredReadTest.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterProfileAssuredSupport.java
  backend/baton/src/test/java/touch/baton/config/AssuredTestConfig.java
  backend/baton/src/test/java/touch/baton/document/profile/supporter/read/SupporterProfileReadApiTest.java
  backend/baton/src/test/java/touch/baton/domain/supporter/repository/SupporterRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/supporter/service/SupporterServiceTest.java
Labels: ✨ feat, 💙 BE

#303 dotenv 환경변수 설정
  .github/workflows/frontend_dev_cd.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/constants/index.ts
  frontend/webpack/webpack.common.js
Labels: ✨ feat, ❤️ FE, 🔧 fix

#308 로그인한 맴버 조회 API 구현
  backend/baton/src/docs/asciidoc/MemberLoginProfileReadApi.adoc
  backend/baton/src/main/java/touch/baton/config/converter/ConverterConfig.java
  backend/baton/src/main/java/touch/baton/domain/member/controller/MemberProfileController.java
  backend/baton/src/main/java/touch/baton/domain/member/controller/response/LoginMemberInfoResponse.java
  backend/baton/src/test/java/touch/baton/assure/member/MemberProfileAssuredReadTest.java
  backend/baton/src/test/java/touch/baton/assure/member/MemberProfileAssuredSupport.java
  backend/baton/src/test/java/touch/baton/config/MockMvcTest.java
  backend/baton/src/test/java/touch/baton/config/RestdocsConfig.java
  backend/baton/src/test/java/touch/baton/config/converter/ConverterConfigTest.java
  backend/baton/src/test/java/touch/baton/document/oauth/github/GithubOauthApiTest.java
  backend/baton/src/test/java/touch/baton/document/profile/member/read/MemberLoginProfileReadApiTest.java
  backend/baton/src/test/java/touch/baton/document/profile/supporter/read/SupporterProfileReadApiTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadApiTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/MemberFixture.java
Labels: ✨ feat, 💙 BE

#310 러너 본인 프로필 조회 API 구현
  backend/baton/src/docs/asciidoc/RunnerProfileReadApi.adoc
  backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
  backend/baton/src/main/java/touch/baton/domain/runner/controller/RunnerProfileController.java
  backend/baton/src/main/java/touch/baton/domain/runner/controller/response/RunnerResponse.java
  backend/baton/src/test/java/touch/baton/assure/runner/RunnerProfileAssuredReadTest.java
  backend/baton/src/test/java/touch/baton/assure/runner/RunnerProfileAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredReadTest.java
  backend/baton/src/test/java/touch/baton/config/AssuredTestConfig.java
  backend/baton/src/test/java/touch/baton/config/AssuredTestExecutionListener.java
  backend/baton/src/test/java/touch/baton/document/profile/runner/read/RunnerProfileReadApiTest.java
  backend/baton/src/test/java/touch/baton/domain/runner/RunnerTest.java
  backend/baton/src/test/java/touch/baton/domain/runner/repository/RunnerRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/RunnerPostTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/controller/read/RunnerPostControllerReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostRepositoryDeleteTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostRepositoryReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceReadTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/RunnerPostTagTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/RunnerPostTagsTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/repository/RunnerPostTagRepositoryTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerTechnicalTagsFixture.java
Labels: ✨ feat, 💙 BE

#311 러너 프로필 조회 API 구현
  backend/baton/src/docs/asciidoc/RunnerProfileReadApi.adoc
  backend/baton/src/main/java/touch/baton/domain/common/response/ErrorResponse.java
  backend/baton/src/main/java/touch/baton/domain/member/Member.java
  backend/baton/src/main/java/touch/baton/domain/oauth/OauthInformation.java
  backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
  backend/baton/src/main/java/touch/baton/domain/runner/controller/RunnerProfileController.java
  backend/baton/src/main/java/touch/baton/domain/runner/controller/response/RunnerProfileResponse.java
  backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerService.java
  backend/baton/src/main/java/touch/baton/domain/technicaltag/repository/TechnicalTagRepository.java
  backend/baton/src/main/java/touch/baton/infra/auth/oauth/github/client/GithubInformationClient.java
  backend/baton/src/main/java/touch/baton/infra/auth/oauth/github/response/GithubMemberResponse.java
  backend/baton/src/test/java/touch/baton/assure/feedback/SupporterFeedbackAssuredCreateTest.java
  backend/baton/src/test/java/touch/baton/assure/runner/RunnerProfileAssuredReadTest.java
  backend/baton/src/test/java/touch/baton/assure/runner/RunnerProfileAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredDeleteTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredReadTest.java
  backend/baton/src/test/java/touch/baton/config/AssuredTestConfig.java
  backend/baton/src/test/java/touch/baton/config/RestdocsConfig.java
  backend/baton/src/test/java/touch/baton/config/ServiceTestConfig.java
  backend/baton/src/test/java/touch/baton/document/oauth/github/GithubOauthApiTest.java
  backend/baton/src/test/java/touch/baton/document/profile/runner/read/RunnerProfileReadApiTest.java
  backend/baton/src/test/java/touch/baton/document/profile/supporter/read/SupporterProfileReadApiTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadApiTest.java
  backend/baton/src/test/java/touch/baton/domain/member/MemberTest.java
  backend/baton/src/test/java/touch/baton/domain/runner/service/RunnerServiceReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/RunnerPostTest.java
  backend/baton/src/test/java/touch/baton/domain/supporter/service/SupporterServiceTest.java
  backend/baton/src/test/java/touch/baton/domain/technicaltag/TechnicalTagTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerFixture.java
Labels: ✨ feat, 💙 BE

#306 러너 게시물 생성 페이지 수정 ( 마감기한 입력 )
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/src/utils/date.ts
Labels: ✨ feat, ❤️ FE, ♻️ refactor

#269 태그 입력 수정
  frontend/src/components/TagInput/TagInput.tsx
Labels: ✨ feat, ❤️ FE, 🔧 fix

#314 채팅방 아이콘을 사람 아이콘으로 변경
  frontend/src/assets/applicant-icon.svg
  frontend/src/assets/chatting-icon.svg
  frontend/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  frontend/src/mocks/data/runnerPostDetails.json
  frontend/src/mocks/data/runnerPostList.json
  frontend/src/pages/RunnerPostDetailPage.tsx
  frontend/src/types/runnerPost.ts
Labels: ✨ feat, ❤️ FE, 💄 design

#319 API 요청 메서드 분리
  frontend/src/api/fetch.ts
  frontend/src/components/RunnerPost/RunnerPostList/RunnerPostList.tsx
Labels: ✨ feat, ❤️ FE, ♻️ refactor

#313 웹팩 플러그인 설정 수정
  frontend/webpack/webpack.common.js
  frontend/webpack/webpack.prod.js
Labels: 🔧 fix

#329 만들어진 restdocs 파일을 src/resources/static/docs/ 하위로 이동
  backend/baton/.gitignore
  backend/baton/build.gradle
  backend/baton/src/docs/asciidoc/MemberLoginProfileReadApi.adoc
  backend/baton/src/docs/asciidoc/RunnerProfileReadApi.adoc
  backend/baton/src/docs/asciidoc/SupporterProfileUpdateApi.adoc
  backend/baton/src/docs/asciidoc/index.adoc
Labels: ✨ feat, 💙 BE

#325 Runner profile 수정 API 구현
  backend/baton/src/docs/asciidoc/RunnerProfileUpdateApi.adoc
  backend/baton/src/main/java/touch/baton/domain/common/vo/Introduction.java
  backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
  backend/baton/src/main/java/touch/baton/domain/runner/controller/RunnerProfileController.java
  backend/baton/src/main/java/touch/baton/domain/runner/controller/response/RunnerProfileResponse.java
  backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerService.java
  backend/baton/src/main/java/touch/baton/domain/runner/service/dto/RunnerUpdateRequest.java
  backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
  backend/baton/src/main/java/touch/baton/domain/supporter/service/dto/SupporterUpdateRequest.java
  backend/baton/src/main/java/touch/baton/domain/technicaltag/repository/RunnerTechnicalTagRepository.java
  backend/baton/src/test/java/touch/baton/assure/runner/RunnerProfileAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runner/RunnerProfileAssuredUpdateTest.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterProfileAssuredSupport.java
  backend/baton/src/test/java/touch/baton/config/ServiceTestConfig.java
  backend/baton/src/test/java/touch/baton/document/profile/runner/read/RunnerProfileReadApiTest.java
  backend/baton/src/test/java/touch/baton/document/profile/runner/update/RunnerProfileUpdateApiTest.java
  backend/baton/src/test/java/touch/baton/domain/runner/service/RunnerServiceReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runner/service/RunnerServiceUpdateTest.java
  backend/baton/src/test/java/touch/baton/domain/supporter/service/SupporterServiceTest.java
Labels: ✨ feat, 💙 BE

#327 ConfirmModal 문구 수정 및 esc 기능 추가
  frontend/src/components/ConfirmModal/ConfirmModal.tsx
Labels: ✨ feat, ❤️ FE

#312 서포터 선택 페이지 구현
  frontend/src/components/SelectSupportModal/SelectSupportModal.tsx
  frontend/src/components/SelectedSupporter/SelectedSupporter.tsx
  frontend/src/components/SupporterCard/SupporterCardItem/SupporterCardItem.tsx
  frontend/src/components/SupporterCard/SupporterCartList/SupporterCardList.tsx
  frontend/src/components/SupporterSelect/SupporterSelectItem/SupporterSelectItem.tsx
  frontend/src/components/SupporterSelect/SupporterSelectList/SupporterSelectList.tsx
  frontend/src/mocks/data/supporterCandidate.json
  frontend/src/mocks/handlers.ts
  frontend/src/pages/SupporterSelectPage.tsx
  frontend/src/router.tsx
  frontend/src/types/supporterCandidate.ts
  frontend/src/types/supporterCard.ts
Labels: ✨ feat, ❤️ FE

#337 서포터의 리뷰 제안 철회 API 구현
  backend/baton/src/docs/asciidoc/MemberLoginProfileReadApi.adoc
  backend/baton/src/docs/asciidoc/RunnerLoginProfileReadApi.adoc
  backend/baton/src/docs/asciidoc/RunnerPostReadApi.adoc
  backend/baton/src/docs/asciidoc/RunnerPostUpdateApplicantCancelationApi.adoc
  backend/baton/src/docs/asciidoc/RunnerProfileReadApi.adoc
  backend/baton/src/docs/asciidoc/RunnerProfileUpdateApi.adoc
  backend/baton/src/docs/asciidoc/SupporterProfileUpdateApi.adoc
  backend/baton/src/docs/asciidoc/index.adoc
  backend/baton/src/main/java/touch/baton/BatonApplication.java
  backend/baton/src/main/java/touch/baton/domain/common/exception/ClientErrorCode.java
  backend/baton/src/main/java/touch/baton/domain/common/exception/DomainException.java
  backend/baton/src/main/java/touch/baton/domain/common/exception/validator/ValidNotNull.java
  backend/baton/src/main/java/touch/baton/domain/common/vo/TagName.java
  backend/baton/src/main/java/touch/baton/domain/oauth/repository/OauthRunnerRepository.java
  backend/baton/src/main/java/touch/baton/domain/oauth/repository/OauthSupporterRepository.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/RunnerPost.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/exception/validator/ValidFuture.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/exception/validator/ValidMaxLength.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/vo/ReviewStatus.java
  backend/baton/src/main/java/touch/baton/domain/supporter/SupporterRunnerPost.java
  backend/baton/src/main/java/touch/baton/domain/supporter/repository/SupporterRunnerPostRepository.java
  backend/baton/src/main/resources/application.yml
  backend/baton/src/test/java/touch/baton/BatonApplicationTests.java
  backend/baton/src/test/java/touch/baton/TestBatonApplication.java
  backend/baton/src/test/java/touch/baton/assure/common/AssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithLoginedAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterRunnerPostAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterRunnerPostDeleteAssuredTest.java
  backend/baton/src/test/java/touch/baton/config/AssuredTestConfig.java
  backend/baton/src/test/java/touch/baton/config/ServiceTestConfig.java
  backend/baton/src/test/java/touch/baton/document/profile/supporter/update/SupporterProfileUpdateApiTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostUpdateApplicantCancelationApiTest.java
  backend/baton/src/test/java/touch/baton/domain/common/vo/WatchedCountTest.java
  backend/baton/src/test/java/touch/baton/domain/feedback/service/FeedbackServiceTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostUpdateApplicantCancelationServiceTest.java
  backend/baton/src/test/java/touch/baton/domain/supporter/SupporterTest.java
  backend/baton/src/test/java/touch/baton/domain/supporter/repository/SupporterRunnerPostRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/technicaltag/repository/TechnicalTagRepositoryTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerPostFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerPostTagsFixture.java
  backend/baton/src/test/java/touch/baton/fixture/domain/SupporterFixture.java
Labels: ✨ feat, 💙 BE

#340 서포터가 러너 게시글 리뷰 신청 API 구현
  backend/baton/src/docs/asciidoc/RunnerPostCreateReadApi.adoc
  backend/baton/src/docs/asciidoc/RunnerPostUpdateApi.adoc
  backend/baton/src/docs/asciidoc/RunnerProfileReadApi.adoc
  backend/baton/src/main/java/touch/baton/domain/common/exception/ClientErrorCode.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerPostResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/dto/RunnerPostApplicantCreateRequest.java
  backend/baton/src/main/java/touch/baton/domain/supporter/repository/SupporterRunnerPostRepository.java
  backend/baton/src/test/java/touch/baton/assure/common/AssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredCreateSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredCreateTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/create/RunnerPostCreateApiTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadApiTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceCreateTest.java
  backend/baton/src/test/java/touch/baton/domain/supporter/repository/SupporterRunnerPostRepositoryTest.java
Labels: ✨ feat, 💙 BE

#350 러너 게시글 삭제 API
  backend/baton/src/docs/asciidoc/RunnerPostDeleteApi.adoc
  backend/baton/src/docs/asciidoc/index.adoc
  backend/baton/src/main/java/touch/baton/domain/runnerpost/RunnerPost.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/vo/ReviewStatus.java
  backend/baton/src/main/java/touch/baton/domain/supporter/repository/SupporterRunnerPostRepository.java
  backend/baton/src/test/java/touch/baton/assure/common/AssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredDeleteTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostDeleteAssuredTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/delete/RunnerPostDeleteApiTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceCreateTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceDeleteTest.java
  backend/baton/src/test/java/touch/baton/domain/supporter/repository/SupporterRunnerPostRepositoryTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerPostFixture.java
Labels: ✨ feat, 💙 BE, ♻️ refactor

#345 서포터 본인 프로필 조회 API를 구현
  backend/baton/src/docs/asciidoc/SupporterProfileReadApi.adoc
  backend/baton/src/docs/asciidoc/index.adoc
  backend/baton/src/main/java/touch/baton/domain/supporter/controller/SupporterProfileController.java
  backend/baton/src/main/java/touch/baton/domain/supporter/controller/response/SupporterResponse.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterProfileAssuredReadTest.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterProfileAssuredSupport.java
  backend/baton/src/test/java/touch/baton/document/profile/supporter/read/SupporterProfileReadApiTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/SupporterFixture.java
Labels: ✨ feat, 💙 BE

#343 러너 게시글 상세 조회 API 리팩터링
  backend/baton/src/docs/asciidoc/RunnerPostReadApi.adoc
  backend/baton/src/docs/asciidoc/index.adoc
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerPostResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/main/java/touch/baton/domain/supporter/repository/SupporterRunnerPostRepository.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredCreateTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithLoginedAssuredTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadApiTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/controller/read/RunnerPostControllerReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceReadTest.java
Labels: ✨ feat, 💙 BE, ♻️ refactor

#333 Toast 기능 구현
  frontend/.storybook/preview-body.html
  frontend/public/index.html
  frontend/src/assets/complete-icon.svg
  frontend/src/assets/error-icon.svg
  frontend/src/components/common/Toast/Toast.stories.ts
  frontend/src/components/common/Toast/Toast.tsx
  frontend/src/hooks/useToast.ts
Labels: ✨ feat, ❤️ FE

#347 서포터가 본인이 리뷰한 게시글의 상태를 리뷰 완료로 변경하는 API 구현
  backend/baton/src/docs/asciidoc/RunnerPostUpdateApi.adoc
  backend/baton/src/docs/asciidoc/index.adoc
  backend/baton/src/main/java/touch/baton/domain/runnerpost/RunnerPost.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredUpdateTest.java
  backend/baton/src/test/java/touch/baton/config/AssuredTestConfig.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/update/RunnerPostUpdateApiTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceUpdateTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerPostFixture.java
Labels: ✨ feat, 💙 BE

#342 로그인한 서포터의 러너 게시글 조회 API 구현
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerPostReadResponses.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerPostResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/repository/RunnerPostRepository.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/vo/ReviewStatus.java
  backend/baton/src/test/java/touch/baton/assure/common/AssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/feedback/SupporterFeedbackAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/feedback/SupporterFeedbackCreateAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/member/MemberAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/member/MemberReadWithLoginedMemberAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runner/RunnerAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runner/RunnerProfileAssuredReadTest.java
  backend/baton/src/test/java/touch/baton/assure/runner/RunnerReadByRunnerIdAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runner/RunnerReadWithLoginedRunnerAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runner/RunnerUpdateAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadByRunnerPostIdAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithLoginedSupporterAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithSupporterIdAndReviewStatusAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterReadBySupporterIdAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterUpdateAssuredTest.java
  backend/baton/src/test/java/touch/baton/controller/runner/RunnerAssuredSupport.java
  backend/baton/src/test/java/touch/baton/controller/runner/RunnerProfileAssuredReadTest.java
  backend/baton/src/test/java/touch/baton/document/profile/member/read/MemberReadWithLoginedMemberApiTest.java
  backend/baton/src/test/java/touch/baton/document/profile/runner/read/RunnerReadByGuestApiTest.java
  backend/baton/src/test/java/touch/baton/document/profile/runner/read/RunnerReadByRunnerIdApiTest.java
  backend/baton/src/test/java/touch/baton/document/profile/runner/read/RunnerReadWithLoginedRunnerApiTest.java
  backend/baton/src/test/java/touch/baton/document/profile/runner/update/RunnerUpdateApiTest.java
  backend/baton/src/test/java/touch/baton/document/profile/supporter/read/SupporterReadByGuestApiTest.java
  backend/baton/src/test/java/touch/baton/document/profile/supporter/update/SupporterUpdateApiTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadAllApiTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadOfSupporterByGuestApiTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadWithLoginedSupporterApiTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/read/RunnerPostRepositoryReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceReadTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerPostFixture.java
Labels: ✨ feat, 💙 BE

#330 프로필 수정 페이지 구현
  frontend/src/assets/technicalLabelIcon.tsx
  frontend/src/components/InputBox/InputBox.tsx
  frontend/src/components/TechLabelButton/TechLabelButton.tsx
  frontend/src/components/TechTagSelectModal/TechTagSelectModal.tsx
  frontend/src/components/Textarea/Textarea.tsx
  frontend/src/constants/tags.ts
  frontend/src/mocks/data/runnerProfileInfo.json
  frontend/src/mocks/data/supporterProfileInfo.json
  frontend/src/mocks/handlers.ts
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/router.tsx
  frontend/src/types/profile.ts
  frontend/src/types/tags.ts
  frontend/src/utils/object.ts
Labels: ✨ feat, ❤️ FE

#348 러너 게시글 생성 API 수정
  backend/baton/src/docs/asciidoc/RunnerPostCreateApi.adoc
  backend/baton/src/docs/asciidoc/index.adoc
  backend/baton/src/main/java/touch/baton/domain/runnerpost/exception/validator/FutureValidator.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/exception/validator/MaxLengthValidator.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/test/java/touch/baton/assure/common/AssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostCreateAssuredTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/post/RunnerPostCreateApiTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/controller/RunnerPostControllerCreateTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceCreateTest.java
Labels: 💙 BE, ♻️ refactor

#359 Restdocs가 build 파일에 생성이 되지 않던 문제 수정
  backend/baton/build.gradle
  backend/baton/src/docs/asciidoc/MemberLoginProfileReadApi.adoc
  backend/baton/src/docs/asciidoc/RunnerLoginProfileReadApi.adoc
  backend/baton/src/docs/asciidoc/RunnerPostReadApi.adoc
  backend/baton/src/docs/asciidoc/RunnerPostUpdateApplicantCancelationApi.adoc
  backend/baton/src/docs/asciidoc/RunnerProfileReadApi.adoc
  backend/baton/src/docs/asciidoc/RunnerProfileUpdateApi.adoc
  backend/baton/src/docs/asciidoc/SupporterProfileReadApi.adoc
  backend/baton/src/docs/asciidoc/SupporterProfileUpdateApi.adoc
  backend/baton/src/docs/asciidoc/index.adoc
Labels: 💙 BE, ♻️ refactor, 🔧 fix

#361 build.gradle에서 RESTDocs 파일 변수명 수정
  backend/baton/build.gradle
Labels: 🐛 bug, 💙 BE

#362 build.gradle에서 RESTDocs 파일 변수명 수정
  backend/baton/build.gradle
Labels: 🐛 bug, 💙 BE, ♻️ refactor

#365 러너 게시글 상세 조회 서포터 리뷰 지원 유무 응답 추가 및 uri 수정
  backend/baton/src/docs/asciidoc/RunnerPostReadApi.adoc
  backend/baton/src/main/java/touch/baton/domain/runnerpost/RunnerPost.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerPostResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/main/java/touch/baton/domain/supporter/repository/SupporterRunnerPostRepository.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredCreateSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredCreateTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadByRunnerPostIdAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithLoginedAssuredTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/create/RunnerPostCreateApiTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadAllApiTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadOneApiTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceReadTest.java
  backend/baton/src/test/java/touch/baton/domain/supporter/repository/SupporterRunnerPostRepositoryTest.java
Labels: 🐛 bug, 💙 BE

#344 러너 게시글 전체 조회 API 페이징 기능 추가
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerPostResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/repository/RunnerPostRepository.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadAssuredTest.java
  backend/baton/src/test/java/touch/baton/document/profile/member/read/MemberReadWithLoginedMemberApiTest.java
  backend/baton/src/test/java/touch/baton/document/profile/runner/read/RunnerReadByGuestApiTest.java
  backend/baton/src/test/java/touch/baton/document/profile/runner/read/RunnerReadWithLoginedRunnerApiTest.java
  backend/baton/src/test/java/touch/baton/document/profile/runner/update/RunnerUpdateApiTest.java
  backend/baton/src/test/java/touch/baton/document/profile/supporter/update/SupporterUpdateApiTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/create/RunnerPostCreateApiTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadAllApiTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadOfSupporterByGuestApiTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadWithLoginedSupporterApiTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/read/RunnerPostRepositoryReadTest.java
Labels: ✨ feat, 💙 BE

#376 api 공통 메서드 수정
  frontend/src/api/fetch.ts
  frontend/src/components/RunnerPost/RunnerPostList/RunnerPostList.tsx
  frontend/src/mocks/handlers.ts
Labels: ✨ feat, ❤️ FE, ♻️ refactor

#379 Toast에 Context API 적용
  frontend/src/App.tsx
  frontend/src/components/common/Toast/Toast.stories.ts
  frontend/src/components/common/Toast/Toast.tsx
  frontend/src/contexts/ToastContext.tsx
  frontend/src/hooks/useToast.ts
Labels: ✨ feat, ❤️ FE, ♻️ refactor

#380 러너 글 작성 PR 주소 유효성 검증
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/src/utils/validate.ts
Labels: ✨ feat, ❤️ FE

#364 프로필 상세 보기 페이지 구현 (러너, 서포터)
  frontend/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  frontend/src/components/SupporterCard/SupporterCardItem/SupporterCardItem.tsx
  frontend/src/components/SupporterCard/SupporterCartList/SupporterCardList.tsx
  frontend/src/hooks/usePageRouter.ts
  frontend/src/mocks/data/runnerProfileInfo.json
  frontend/src/mocks/data/supporterProfileInfo.json
  frontend/src/mocks/data/supporterProfilePost.json
  frontend/src/mocks/handlers.ts
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/RunnerPostDetailPage.tsx
  frontend/src/pages/RunnerProfilePage.tsx
  frontend/src/pages/SupporterProfilePage.tsx
  frontend/src/router.tsx
  frontend/src/types/profile.ts
  frontend/src/types/runnerPost.ts
Labels: ✨ feat, ❤️ FE

#366 후기 작성 페이지 구현
  frontend/src/assets/checkboxIcon.tsx
  frontend/src/assets/feedback-icon/bad-feedback-gray-icon.svg
  frontend/src/assets/feedback-icon/bad-feedback-icon.svg
  frontend/src/assets/feedback-icon/good-feedback-gray-icon.svg
  frontend/src/assets/feedback-icon/good-feedback-icon.svg
  frontend/src/assets/feedback-icon/great-feedback-gray-icon.svg
  frontend/src/assets/feedback-icon/great-feedback-icon.svg
  frontend/src/assets/letter-icon.svg
  frontend/src/components/CheckBox/CheckBox.tsx
  frontend/src/components/ReviewTypeButton/ReviewTypeButton.tsx
  frontend/src/constants/feedback.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/SupporterFeedbackPage.tsx
  frontend/src/router.tsx
  frontend/src/types/feedback.ts
Labels: ✨ feat, ❤️ FE

#384 분리된 fetch 적용안된 컴포넌트 수정
  frontend/src/components/RunnerPost/RunnerPostList/RunnerPostList.tsx
  frontend/src/components/SupporterCard/SupporterCardItem/SupporterCardItem.tsx
  frontend/src/layout/Header.tsx
  frontend/src/mocks/data/headerProfile.json
  frontend/src/mocks/handlers.ts
  frontend/src/pages/GithubCallbackPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/src/pages/RunnerPostDetailPage.tsx
  frontend/src/types/profile.ts
Labels: ❤️ FE, ♻️ refactor

#386 배포용 api uri 적용
  frontend/src/components/RunnerPost/RunnerPostList/RunnerPostList.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/src/pages/RunnerPostDetailPage.tsx
Labels: ✨ feat, ❤️ FE

#388 fetch content-type 수정
  frontend/src/api/fetch.ts
Labels: ❤️ FE, 🔧 fix

#385 메인페이지 더보기 기능 추가
  frontend/src/components/RunnerPost/RunnerPostList/RunnerPostList.tsx
  frontend/src/mocks/data/runnerPostList.json
  frontend/src/pages/MainPage.tsx
  frontend/src/types/runnerPost.ts
Labels: ✨ feat, ❤️ FE

#389 서포터 마이페이지 버튼 기능 추가 (제안취소, 리뷰완료)
  frontend/src/api/fetch.ts
  frontend/src/components/MyPage/MyPagePostButton/MyPagePostButton.tsx
  frontend/src/components/MyPage/MyPagePostItem/MyPagePostItem.tsx
  frontend/src/hooks/usePageRouter.ts
  frontend/src/mocks/data/myPageRunnerPost.json
  frontend/src/pages/MyPage.tsx
  frontend/src/types/myPage.ts
Labels: ✨ feat, ❤️ FE

#397 MSW 버전 업
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
Labels: ❤️ FE, 🔧 fix

#399 마이페이지 게시글 uri 수정 및 필터 삭제
  frontend/src/components/MyPage/MyPagePostList/MyPagePostList.tsx
  frontend/src/mocks/data/myPagePost/done.json
  frontend/src/mocks/data/myPagePost/inProgress.json
  frontend/src/mocks/data/myPagePost/notStarted.json
  frontend/src/mocks/data/supporterCardList.json
  frontend/src/mocks/handlers.ts
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/types/myPage.ts
Labels: ✨ feat, ❤️ FE, 🔧 fix

#398 PR url에 검증 기능 추가
  backend/baton/src/main/java/touch/baton/domain/common/exception/ClientErrorCode.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/exception/validator/UrlValidator.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/exception/validator/ValidNotUrl.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/dto/RunnerPostCreateRequest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/exception/validator/UrlValidatorTest.java
Labels: ✨ feat, 💙 BE

#392 deploy cd script에 docker mount를 추가
  .github/workflows/deploy-be-ci-cd-push.yml
Labels: ✨ feat, 💙 BE

#403 토스트 메세지 적용 및 에러 핸들링 수정
  frontend/src/api/fetch.ts
  frontend/src/components/SupporterCard/SupporterCardItem/SupporterCardItem.tsx
  frontend/src/components/SupporterCard/SupporterCartList/SupporterCardList.tsx
  frontend/src/components/common/Tag/Tag.tsx
  frontend/src/constants/message.ts
  frontend/src/hooks/useToken.ts
  frontend/src/layout/Header.tsx
  frontend/src/pages/GithubCallbackPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/src/pages/RunnerPostDetailPage.tsx
  frontend/src/pages/RunnerProfilePage.tsx
  frontend/src/pages/SupporterFeedbackPage.tsx
  frontend/src/pages/SupporterProfilePage.tsx
  frontend/src/utils/validate.ts
Labels: ✨ feat, ❤️ FE, ♻️ refactor

#402 로고 이미지 및 메인 색상 변경 + 폰트 CDN 추가
  frontend/src/assets/fonts/PretendardVariable.woff2
  frontend/src/assets/logo-image.svg
  frontend/src/styles/GlobalStyles.ts
  frontend/webpack/webpack.common.js
Labels: ❤️ FE, 💄 design, ♻️ refactor

#405 프로필 수정하기 기능 연결
  frontend/src/assets/technicalLabelIcon.tsx
  frontend/src/components/SupporterCard/SupporterCardItem/SupporterCardItem.tsx
  frontend/src/components/TechTagSelectModal/TechTagSelectModal.tsx
  frontend/src/constants/message.ts
  frontend/src/hooks/usePageRouter.ts
  frontend/src/layout/Header.tsx
  frontend/src/mocks/data/myPageRunnerProfile.json
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/ProfileEditPage.tsx
Labels: ❤️ FE, 💄 design, ♻️ refactor

#408 PageableDefault 의 page default 값을 0으로 시작하도록 수정
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
Labels: 🐛 bug, 💙 BE

#410 필요 없는 메소드 삭제
  backend/baton/src/main/java/touch/baton/common/schedule/SchedulerService.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
  backend/baton/src/test/java/touch/baton/assure/feedback/SupporterFeedbackAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/feedback/SupporterFeedbackCreateAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredCreateSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostUpdateAssuredTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/create/RunnerPostApplicantApiTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/create/RunnerPostCreateApiTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/post/RunnerPostCreateApiTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadOfSupporterByGuestApiTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/SupporterRunnerPostReadApiTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceUpdateTest.java
  backend/baton/src/test/java/touch/baton/fixture/repository/MemberRepositoryFixture.java
  backend/baton/src/test/java/touch/baton/fixture/repository/RunnerPostRepositoryFixture.java
  backend/baton/src/test/java/touch/baton/fixture/repository/RunnerRepositoryFixture.java
  backend/baton/src/test/java/touch/baton/fixture/repository/SupporterRepositoryFixture.java
  backend/baton/src/test/java/touch/baton/fixture/repository/TagRepositoryFixture.java
Labels: 💙 BE, ♻️ refactor

#412 백엔드 리드미 업데이트
  README.md
Labels: 📗 docs, 💙 BE

#414 러너 게시글 상세 페이지 isOwner 응답 수정
  backend/baton/src/main/java/touch/baton/domain/runnerpost/RunnerPost.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
Labels: 🐛 bug, 💙 BE

#415 docs: 기존 Restdocs 정리
  backend/baton/src/docs/asciidoc/MemberLoginReadApi.adoc
  backend/baton/src/docs/asciidoc/RunneReadApi.adoc
  backend/baton/src/docs/asciidoc/RunnerLoginReadApi.adoc
  backend/baton/src/docs/asciidoc/RunnerPostCreateApi.adoc
  backend/baton/src/docs/asciidoc/RunnerPostCreateReadApi.adoc
  backend/baton/src/docs/asciidoc/RunnerPostDeleteApi.adoc
  backend/baton/src/docs/asciidoc/RunnerPostReadApi.adoc
  backend/baton/src/docs/asciidoc/RunnerPostUpdateApi.adoc
  backend/baton/src/docs/asciidoc/RunnerPostUpdateApplicantCancelationApi.adoc
  backend/baton/src/docs/asciidoc/RunnerUpdateApi.adoc
  backend/baton/src/docs/asciidoc/SupporterReadApi.adoc
  backend/baton/src/docs/asciidoc/SupporterUpdateApi.adoc
  backend/baton/src/docs/asciidoc/index.adoc
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadAllApiTest.java
Labels: 📗 docs, 💙 BE

#418 배포 전 오류 수정
  .github/workflows/frontend_prod_cd.yml
  frontend/src/assets/technicalLabelIcon.tsx
  frontend/src/components/ListFilter/ListFilter.tsx
  frontend/src/components/MyPage/MyPagePostButton/MyPagePostButton.tsx
  frontend/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  frontend/src/constants/message.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/GithubCallbackPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/src/pages/RunnerProfilePage.tsx
  frontend/src/pages/SupporterFeedbackPage.tsx
  frontend/src/pages/SupporterProfilePage.tsx
Labels: ❤️ FE, 🔧 fix

#419 [hotfix] 페이지 계속 추가되는 오류 수정
  frontend/src/pages/MyPage.tsx
Labels: ❤️ FE, 🔧 fix

#421 마감기한 지남 (OVERDUE) 라벨 추가
  frontend/src/components/MyPage/MyPagePostItem/MyPagePostItem.tsx
  frontend/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  frontend/src/constants/index.ts
  frontend/src/pages/RunnerPostDetailPage.tsx
  frontend/src/types/runnerPost.ts
Labels: ✨ feat, ❤️ FE, 🔧 fix

#422 [hotfix] 피드백 제출 토스트 문구 수정
  frontend/src/constants/message.ts
  frontend/src/pages/SupporterFeedbackPage.tsx
Labels: ❤️ FE, 🔧 fix

#426 Assured Test 리팩터링
  backend/baton/src/test/java/touch/baton/assure/common/AssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/common/PathParams.java
  backend/baton/src/test/java/touch/baton/assure/common/QueryParams.java
  backend/baton/src/test/java/touch/baton/assure/feedback/SupporterFeedbackAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/feedback/SupporterFeedbackCreateAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/member/MemberAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/member/MemberReadWithLoginedMemberAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runner/RunnerAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runner/RunnerReadWithLoginedRunnerAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runner/RunnerUpdateAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredCreateSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredCreateTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostCreateAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostDeleteAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadByRunnerPostIdAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithLoginedAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithLoginedSupporterAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithSupporterIdAndReviewStatusAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostUpdateAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterReadBySupporterIdAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterRunnerPostAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterRunnerPostDeleteAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterUpdateAssuredTest.java
Labels: 💙 BE, ♻️ refactor
