Repository woowacourse-teams/2023-baton, pull requests merged in 2023-09, with the labels that each got.

#436 Pagenation을 할 때 hasNext가 항상 false인 문제 해결
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
Labels: 🐛 bug, 💙 BE, 🔧 fix

#435 TagReducedName 추가
  backend/baton/src/main/java/touch/baton/domain/tag/RunnerPostTag.java
  backend/baton/src/main/java/touch/baton/domain/tag/Tag.java
  backend/baton/src/main/java/touch/baton/domain/tag/vo/TagReducedName.java
  backend/baton/src/test/java/touch/baton/domain/common/vo/TagNameTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceReadTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/RunnerPostTagTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/TagTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/repository/RunnerPostTagRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/repository/TagRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/vo/TagReducedNameTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/TagFixture.java
Labels: ✨ feat, 💙 BE

#441 데이터베이스 컬럼과 entity 컬럼의 이름과 순서를 일치하게 변경
  backend/baton/src/main/java/touch/baton/domain/common/vo/WatchedCount.java
Labels: 💙 BE, ♻️ refactor

#445 dev self hosted runner에 이름 추가
  .github/workflows/dev-be-ci-cd-push.yml
Labels: 🐛 bug, 💙 BE

#440 인수 테스트에 소셜 회원가입 인수 테스트 기능 추가 및 수정
  backend/baton/src/main/java/touch/baton/domain/oauth/authcode/AuthCodeRequestUrlProviderComposite.java
  backend/baton/src/main/java/touch/baton/domain/oauth/client/OauthInformationClientComposite.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/repository/RunnerPostRepository.java
  backend/baton/src/main/java/touch/baton/infra/auth/jwt/JwtDecoder.java
  backend/baton/src/main/java/touch/baton/infra/auth/jwt/JwtEncoder.java
  backend/baton/src/test/java/touch/baton/assure/common/AssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/common/JwtTestManager.java
  backend/baton/src/test/java/touch/baton/assure/common/OauthLoginTestManager.java
  backend/baton/src/test/java/touch/baton/assure/feedback/SupporterFeedbackAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/feedback/SupporterFeedbackCreateAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/member/MemberReadWithLoginedMemberAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/oauth/OauthAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/oauth/OauthCreateAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/repository/TestMemberRepository.java
  backend/baton/src/test/java/touch/baton/assure/repository/TestRunnerPostRepository.java
  backend/baton/src/test/java/touch/baton/assure/repository/TestRunnerRepository.java
  backend/baton/src/test/java/touch/baton/assure/repository/TestSupporterRepository.java
  backend/baton/src/test/java/touch/baton/assure/repository/TestSupporterRunnerPostRepository.java
  backend/baton/src/test/java/touch/baton/assure/repository/TestTechnicalTagRepository.java
  backend/baton/src/test/java/touch/baton/assure/runner/RunnerAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runner/RunnerReadByRunnerIdAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runner/RunnerReadWithLoginedRunnerAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runner/RunnerUpdateAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredCreateTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostCreateAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostDeleteAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadByReviewStatus.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadByRunnerPostIdAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithLoginedAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithLoginedSupporterAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithSupporterIdAndReviewStatusAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostUpdateAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterReadBySupporterIdAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterRunnerPostAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterRunnerPostDeleteAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/supporter/SupporterUpdateAssuredTest.java
  backend/baton/src/test/java/touch/baton/config/AssuredTestConfig.java
  backend/baton/src/test/java/touch/baton/config/infra/auth/MockAuthTestConfig.java
  backend/baton/src/test/java/touch/baton/config/infra/auth/jwt/MockJwtConfig.java
  backend/baton/src/test/java/touch/baton/config/infra/auth/oauth/authcode/MockAuthCodeRequestUrlProviderCompositeConfig.java
  backend/baton/src/test/java/touch/baton/config/infra/auth/oauth/authcode/MockAuthCodes.java
  backend/baton/src/test/java/touch/baton/config/infra/auth/oauth/client/MockOauthInformationClientCompositeConfig.java
Labels: 💙 BE, ♻️ refactor

#442 반응형 레이아웃 구현
  frontend/src/assets/logo-image-mobile.svg
  frontend/src/components/ConfirmModal/ConfirmModal.tsx
  frontend/src/components/InputBox/InputBox.tsx
  frontend/src/components/MyPage/MyPagePostItem/MyPagePostItem.tsx
  frontend/src/components/MyPage/MyPagePostList/MyPagePostList.tsx
  frontend/src/components/PostTag/PostTag.tsx
  frontend/src/components/PostTagList/PostTagList.tsx
  frontend/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  frontend/src/components/RunnerPost/RunnerPostList/RunnerPostList.tsx
  frontend/src/components/SendMessageModal/SendMessageModal.tsx
  frontend/src/components/TagInput/TagInput.tsx
  frontend/src/components/common/Avatar/Avatar.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/Label/Label.tsx
  frontend/src/hooks/useViewport.ts
  frontend/src/layout/Header.tsx
  frontend/src/layout/Layout.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/src/pages/RunnerPostDetailPage.tsx
  frontend/src/styles/GlobalStyles.ts
Labels: ❤️ FE, 💄 design

#447 가이드라인 컴포넌트 추가
  frontend/src/assets/arrow-icon.tsx
  frontend/src/components/GuideTextarea/GuideTextarea.tsx
Labels: ✨ feat, ❤️ FE

#443 메인 페이지 필터/검색 구현
  frontend/src/assets/filter-icon.svg
  frontend/src/assets/tag-icon.svg
  frontend/src/components/RunnerPost/RunnerPostFilter/RunnerPostFilter.tsx
  frontend/src/components/RunnerPost/RunnerPostSearchBox/RunnerPostSearchBox.tsx
  frontend/src/constants/index.ts
  frontend/src/mocks/data/tagList.json
  frontend/src/mocks/handlers.ts
  frontend/src/pages/MainPage.tsx
  frontend/src/types/tags.ts
Labels: ✨ feat, ❤️ FE

#457 프론트 CD 설정
  .github/workflows/frontend_dev_cd.yml
Labels: ❤️ FE, 🐳 infra

#463 채널톡 기능 구현
  .github/workflows/frontend_dev_cd.yml
  .github/workflows/frontend_prod_cd.yml
  frontend/.gitignore
  frontend/src/App.tsx
  frontend/src/ChannelService.ts
  frontend/src/constants/index.ts
  frontend/webpack/webpack.common.js
Labels: ✨ feat, ❤️ FE

#470 더보기 이후 필터 변경시 리렌더링이 안되는 문제
  frontend/src/pages/MainPage.tsx
Labels: 🐛 bug, ❤️ FE

#472 더보기 이후 필터 변경시 리렌더링이 안되는 문제
  frontend/src/pages/MainPage.tsx
Labels: 🐛 bug, ❤️ FE

#460 러너 게시물 생성 페이지에 가이드라인 추가
  frontend/src/components/GuideTextarea/GuideTextarea.tsx
  frontend/src/constants/guide.ts
  frontend/src/pages/CreationResultPage.tsx
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/src/router.tsx
  frontend/src/types/runnerPost.ts
  frontend/src/utils/validate.ts
Labels: ✨ feat, ❤️ FE

#454 태그 이름과 리뷰 상태를 조건으로 러너 게시글 페이징 검색 API 구현
  backend/baton/src/docs/asciidoc/RunnerPostReadApi.adoc
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostReadController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/repository/RunnerPostReadRepository.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostReadService.java
  backend/baton/src/main/java/touch/baton/domain/tag/RunnerPostTags.java
  backend/baton/src/test/java/touch/baton/assure/oauth/OauthCreateAssuredTest.java
  backend/baton/src/test/java/touch/baton/assure/repository/TestRunnerPostReadRepository.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadAssuredTest.java
  backend/baton/src/test/java/touch/baton/config/AssuredTestConfig.java
  backend/baton/src/test/java/touch/baton/config/ServiceTestConfig.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadSearchApiTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostReadRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostReadServiceTest.java
Labels: ✨ feat, 💙 BE

#455 미션 레포에 브랜치 생성 기능 구현
  backend/baton/src/docs/asciidoc/GithubBranchCreateApi.adoc
  backend/baton/src/docs/asciidoc/index.adoc
  backend/baton/src/main/java/touch/baton/common/LoggerAspect.java
  backend/baton/src/main/java/touch/baton/domain/common/GlobalControllerAdvice.java
  backend/baton/src/main/java/touch/baton/domain/common/exception/ClientErrorCode.java
  backend/baton/src/main/java/touch/baton/domain/member/controller/MemberBranchController.java
  backend/baton/src/main/java/touch/baton/domain/member/service/dto/GithubBranchManageable.java
  backend/baton/src/main/java/touch/baton/domain/member/service/dto/GithubRepoNameRequest.java
  backend/baton/src/main/java/touch/baton/infra/exception/InfraException.java
  backend/baton/src/main/java/touch/baton/infra/github/GithubBranchManager.java
  backend/baton/src/main/java/touch/baton/infra/github/request/CreateBranchRequest.java
  backend/baton/src/main/java/touch/baton/infra/github/response/ReadBranchInfoResponse.java
  backend/baton/src/main/java/touch/baton/infra/github/response/ReadLastCommitInfoResponse.java
  backend/baton/src/test/java/touch/baton/assure/member/MemberBranchAssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/member/MemberBranchCreateAssuredTest.java
  backend/baton/src/test/java/touch/baton/config/AssuredTestConfig.java
  backend/baton/src/test/java/touch/baton/config/infra/github/MockGithubBranchServiceConfig.java
  backend/baton/src/test/java/touch/baton/document/github/GithubBranchApiTest.java
  backend/baton/src/test/resources/application.yml
Labels: ✨ feat, 💙 BE

#476 로그인시 refreshToken이 중복해서 저장되는 문제 해결
  backend/baton/src/main/java/touch/baton/domain/oauth/repository/RefreshTokenRepository.java
  backend/baton/src/main/java/touch/baton/domain/oauth/service/OauthService.java
  backend/baton/src/main/resources/application-test.yml
  backend/baton/src/test/java/touch/baton/domain/oauth/repository/RefreshTokenRepositoryTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RefreshTokenFixture.java
Labels: 🐛 bug, 💙 BE

#482 게시글 정렬 시 createdAt 이 같다면 id 오름차순으로 정렬되게 보여주는 기능 추가
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/test/java/touch/baton/domain/oauth/repository/RefreshTokenRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/read/RunnerPostRepositoryReadTest.java
  backend/baton/src/test/java/touch/baton/util/TestDateFormatUtil.java
Labels: 💙 BE, ♻️ refactor

#484 리프레시 토큰 적용
  frontend/src/App.tsx
  frontend/src/api/fetch.ts
  frontend/src/api/login.ts
  frontend/src/components/ErrorBoundary/LoginErrorBoundary.tsx
  frontend/src/components/LoginError.tsx
  frontend/src/components/MyPage/MyPagePostButton/MyPagePostButton.tsx
  frontend/src/components/RunnerPost/RunnerPostSearchBox/RunnerPostSearchBox.tsx
  frontend/src/components/SupporterCard/SupporterCardItem/SupporterCardItem.tsx
  frontend/src/components/SupporterCard/SupporterCartList/SupporterCardList.tsx
  frontend/src/hooks/useFetch.ts
  frontend/src/hooks/useLogin.ts
  frontend/src/hooks/usePageRouter.ts
  frontend/src/hooks/useToken.ts
  frontend/src/layout/Header.tsx
  frontend/src/pages/GithubCallbackPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/src/pages/RunnerPostDetailPage.tsx
  frontend/src/pages/RunnerProfilePage.tsx
  frontend/src/pages/SupporterFeedbackPage.tsx
  frontend/src/pages/SupporterProfilePage.tsx
  frontend/src/types/error.ts
  frontend/src/utils/cookie.ts
Labels: ✨ feat, ❤️ FE

#487 dev 서버 도메인 주소 변경
  frontend/src/constants/index.ts
Labels: ❤️ FE, 🐳 infra

#489 Hotfix: 쿠키 관련 로직 제거
  frontend/src/hooks/useFetch.ts
  frontend/src/hooks/useLogin.ts
  frontend/src/utils/cookie.ts
Labels: ❤️ FE

#490 Hotfix: 사용하지 않는 import 제거
  frontend/src/components/SupporterCard/SupporterCardItem/SupporterCardItem.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/useToken.ts
  frontend/src/pages/MainPage.tsx
Labels: ❤️ FE

#491 Hotfix: 채널톡 비활성화
  frontend/src/App.tsx
  frontend/src/ChannelService.ts
Labels: ❤️ FE

#473 메인 페이지 검색창 변경
  frontend/src/assets/tag-icon.svg
  frontend/src/components/RunnerPost/RunnerPostFilter/RunnerPostFilter.tsx
  frontend/src/components/RunnerPost/RunnerPostSearchBox/RunnerPostSearchBox.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/MainPage.tsx
Labels: ✨ feat, ❤️ FE, 💄 design

#477 보스몬스터 이벤트 페이지 구현
  frontend/src/assets/banner/banner_background.png
  frontend/src/assets/banner/event_banner.webp
  frontend/src/assets/banner/event_banner_post.png
  frontend/src/components/Banner/Banner.tsx
  frontend/src/components/ConfirmModal/ConfirmModal.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/constants/message.ts
  frontend/src/hooks/usePageRouter.ts
  frontend/src/layout/Layout.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/NoticePage.tsx
  frontend/src/router.tsx
  frontend/src/types/image.d.ts
  frontend/webpack/webpack.common.js
Labels: ✨ feat, ❤️ FE, 💄 design

#479 파비콘 적용
  frontend/public/favicon.png
  frontend/public/index.html
Labels: ✨ feat, ❤️ FE

#499 게시글 다중 조회 정렬 기준 id 로 변경
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostReadController.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/read/RunnerPostRepositoryReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostReadServiceTest.java
Labels: 💙 BE, ♻️ refactor

#500 토큰 디코딩 오류 해결
  backend/baton/src/main/java/touch/baton/domain/oauth/AuthorizationHeader.java
  backend/baton/src/main/java/touch/baton/domain/oauth/controller/OauthController.java
  backend/baton/src/main/java/touch/baton/domain/oauth/controller/resolver/UserPrincipalArgumentResolver.java
  backend/baton/src/main/java/touch/baton/domain/oauth/service/OauthService.java
  backend/baton/src/main/java/touch/baton/infra/auth/jwt/JwtDecoder.java
  backend/baton/src/test/java/touch/baton/assure/common/AssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/common/JwtTestManager.java
  backend/baton/src/test/java/touch/baton/config/RestdocsConfig.java
  backend/baton/src/test/java/touch/baton/document/oauth/token/RefreshTokenApiTest.java
  backend/baton/src/test/java/touch/baton/domain/oauth/service/OauthServiceUpdateTest.java
  backend/baton/src/test/java/touch/baton/domain/oauth/vo/AuthorizationHeaderTest.java
  backend/baton/src/test/java/touch/baton/fixture/vo/AuthorizationHeaderFixture.java
  backend/baton/src/test/java/touch/baton/infra/auth/jwt/JwtEncoderAndDecoderTest.java
Labels: 🐛 bug, 💙 BE

#510 refresh 를 호출할 때 만료기한을 확인하는 로직 제거
  backend/baton/src/main/java/touch/baton/domain/common/exception/ClientErrorCode.java
  backend/baton/src/main/java/touch/baton/infra/auth/jwt/JwtDecoder.java
  backend/baton/src/test/java/touch/baton/assure/oauth/OauthRefreshTokenAssuredTest.java
Labels: 💙 BE, ♻️ refactor

#507 채널톡 복구
  frontend/src/App.tsx
  frontend/src/ChannelService.ts
Labels: ✨ feat, ❤️ FE

#503 태그 검색 API 수정
  frontend/src/components/RunnerPost/RunnerPostSearchBox/RunnerPostSearchBox.tsx
  frontend/src/mocks/data/emptyRunnerPostList.json
  frontend/src/mocks/data/searchedPostList.json
  frontend/src/mocks/handlers.ts
  frontend/src/pages/MainPage.tsx
  frontend/src/types/tags.ts
Labels: 🐛 bug, ❤️ FE

#508 마이페이지 반응형 디자인 추가
  frontend/src/components/ListFilter/ListFilter.tsx
  frontend/src/components/MyPage/MyPagePostButton/MyPagePostButton.tsx
  frontend/src/components/MyPage/MyPagePostItem/MyPagePostItem.tsx
  frontend/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  frontend/src/components/common/Avatar/Avatar.tsx
  frontend/src/pages/MyPage.tsx
Labels: ❤️ FE, 💄 design, 🔧 fix

#512 JWT 유효기간 계산 로직 오류 수정
  frontend/src/hooks/useLogin.ts
Labels: ❤️ FE

#517 로그인 오류 관련 로직 추가
  frontend/src/hooks/useFetch.ts
  frontend/src/hooks/useLogin.ts
Labels: ✨ feat, ❤️ FE, 🔧 fix

#519 한글 검색 자동완성 버그
  frontend/src/components/RunnerPost/RunnerPostSearchBox/RunnerPostSearchBox.tsx
  frontend/src/mocks/data/tagList.json
Labels: ❤️ FE, 🔧 fix

#525 로그인 토큰 확인 후 App 렌더링
  frontend/src/App.tsx
  frontend/src/hooks/useLogin.ts
  frontend/src/utils/jwt.ts
Labels: ✨ feat, ❤️ FE

#521 api 에러시 보여주는 문구 변경
  frontend/src/hooks/useFetch.ts
Labels: ❤️ FE

#522 레이아웃 시프트 수정
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MyPage.tsx
Labels: ❤️ FE, 💄 design, 🔧 fix

#528 RefreshToken을 재발급 받을 때 현재 시간을 기준으로 발급 받도록 변경
  backend/baton/src/main/java/touch/baton/domain/oauth/token/ExpireDate.java
  backend/baton/src/main/java/touch/baton/domain/oauth/token/RefreshToken.java
  backend/baton/src/test/java/touch/baton/domain/oauth/token/RefreshTokenTest.java
Labels: 🐛 bug, 💙 BE

#530 favicon, 로딩스피너, 반응형 디자인 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/assets/technicalLabelIcon.tsx
  frontend/src/components/RunnerPost/RunnerPostFilter/RunnerPostFilter.tsx
  frontend/src/components/RunnerPost/RunnerPostSearchBox/RunnerPostSearchBox.tsx
  frontend/src/components/common/Avatar/Avatar.tsx
  frontend/src/components/common/Label/Label.tsx
  frontend/src/components/common/Spinner/Spinner.stories.ts
  frontend/src/components/common/Spinner/Spinner.tsx
  frontend/src/layout/Header.tsx
  frontend/src/mocks/data/runnerPostDetails.json
  frontend/src/mocks/data/runnerPostList.json
  frontend/src/pages/LoadingPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/NoticePage.tsx
  frontend/src/pages/RunnerPostDetailPage.tsx
  frontend/src/styles/GlobalStyles.ts
  frontend/webpack/webpack.common.js
Labels: ✨ feat, ❤️ FE, 💄 design

#535 태그+리뷰상태 검색 API와 리뷰 상태만 검색 API 합치기
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostReadController.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadSearchApiTest.java
Labels: 💙 BE, ♻️ refactor

#534 로그인 만료시 에러 메시지 출력
  frontend/src/hooks/useFetch.ts
Labels: ✨ feat, ❤️ FE

#537 tag 검색 시 tagName 이 비었으면 빈 리스트를 반환하도록 변경
  backend/baton/src/main/java/touch/baton/domain/tag/controller/TagController.java
Labels: 💙 BE, ♻️ refactor

#543 글 작성 완료 토스트 출력
  frontend/src/constants/message.ts
  frontend/src/pages/RunnerPostCreatePage.tsx
Labels: ✨ feat, ❤️ FE

#540 깃허브 Redirect 페이지 로딩 적용
  frontend/src/pages/GithubCallbackPage.tsx
  frontend/src/router.tsx
Labels: ✨ feat, ❤️ FE

#541 이벤트 미션 시작 오류 처리
  frontend/src/components/ConfirmModal/ConfirmModal.tsx
  frontend/src/pages/NoticePage.tsx
Labels: ✨ feat, ❤️ FE

#546 글 생성 시 두번 생성되는 오류 수정
  frontend/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/src/pages/RunnerPostDetailPage.tsx
Labels: ✨ feat, ❤️ FE, 💄 design, 🔧 fix

#553 서포터 프로필 페이지 반응형 디자인 추가 및 api 수정
  frontend/src/components/SendMessageModal/SendMessageModal.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/RunnerProfilePage.tsx
  frontend/src/pages/SupporterProfilePage.tsx
  frontend/src/pages/SupporterSelectPage.tsx
Labels: ✨ feat, ❤️ FE, 💄 design

#554 백엔드 머지 작업
  backend/baton/src/main/java/touch/baton/domain/oauth/controller/OauthController.java
Labels: 💙 BE, 🚀 deploy

#557 프론트엔드 CD BASE URL 수정
  .github/workflows/frontend_prod_cd.yml
Labels: ❤️ FE, 🔧 fix

#560 더보기 연속 클릭 및 게시글 검색 API 통일
  frontend/src/mocks/data/emptyRunnerPostList.json
  frontend/src/mocks/data/searchedPostList.json
  frontend/src/mocks/handlers.ts
  frontend/src/pages/MainPage.tsx
Labels: ✨ feat, ❤️ FE, 🔧 fix

#562 반응형 디자인 수정
  frontend/src/components/ConfirmModal/ConfirmModal.tsx
  frontend/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  frontend/src/components/common/Spinner/Spinner.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/NoticePage.tsx
  frontend/src/pages/RunnerPostDetailPage.tsx
Labels: ❤️ FE, 💄 design

#563 github pr 자동 할당 기능 설정
  .github/CODEOWNERS
Labels: ✨ feat, 💙 BE

#555 서포터 피드백 작성 유무 반환 추가, 러너 게시글 조회수 flyway 컬럼명 수정, 서포터 지원자 수 조회시 dto 사용하도록 수정
  backend/baton/src/main/java/touch/baton/domain/runnerpost/RunnerPost.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostReadController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerPostResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/repository/RunnerPostReadRepository.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/repository/dto/ApplicantCountDto.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/repository/dto/ApplicantCountMappingDto.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostReadService.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/vo/IsReviewed.java
  backend/baton/src/main/resources/db/migration/V20230920_1__add_new_runner_post_is_reviewed_column.sql
  backend/baton/src/main/resources/db/migration/V20230920_2__alter_runner_post_watched_count_column_name.sql
  backend/baton/src/test/java/touch/baton/assure/repository/TestRunnerPostReadRepository.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
  backend/baton/src/test/java/touch/baton/common/schedule/ScheduleRunnerPostRepositoryTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadAllApiTest.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadSearchApiTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/RunnerPostTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostReadRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostRepositoryDeleteTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/RunnerPostRepositoryReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/read/RunnerPostRepositoryReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostReadServiceTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceReadTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceUpdateTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostUpdateApplicantCancelationServiceTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/vo/IsReviewedTest.java
  backend/baton/src/test/java/touch/baton/domain/supporter/SupporterFeedbackTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/RunnerPostTagTest.java
  backend/baton/src/test/java/touch/baton/domain/tag/repository/RunnerPostTagRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/technicaltag/repository/SupporterTechnicalTagRepositoryTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerPostFixture.java
Labels: ✨ feat, 💙 BE

#552 이미 서포터 리뷰를 작성했으면 예외 반환하도록 함
  backend/baton/src/main/java/touch/baton/domain/feedback/repository/SupporterFeedbackRepository.java
  backend/baton/src/main/java/touch/baton/domain/feedback/service/FeedbackService.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/RunnerPost.java
  backend/baton/src/test/java/touch/baton/assure/feedback/SupporterFeedbackCreateAssuredTest.java
  backend/baton/src/test/java/touch/baton/domain/feedback/repository/SupporterFeedbackRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/feedback/service/FeedbackServiceTest.java
Labels: 🐛 bug, 💙 BE

#569 마이페이지 제안취소, 리뷰완료 시 해당 게시물 리스트에서 제거
  frontend/src/components/MyPage/MyPagePostButton/MyPagePostButton.tsx
  frontend/src/components/MyPage/MyPagePostItem/MyPagePostItem.tsx
  frontend/src/components/MyPage/MyPagePostList/MyPagePostList.tsx
  frontend/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  frontend/src/components/common/Label/Label.tsx
  frontend/src/mocks/data/myPagePost/done.json
  frontend/src/mocks/data/myPagePost/inProgress.json
  frontend/src/mocks/data/myPagePost/myPagePostList.json
  frontend/src/mocks/data/myPagePost/notStarted.json
  frontend/src/mocks/handlers.ts
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/SupporterSelectPage.tsx
Labels: ✨ feat, ❤️ FE

#572 리프레쉬 토큰 오류 코드 추가, 지원한 서포터 없을 경우 버튼 비활성화
  frontend/src/components/MyPage/MyPagePostButton/MyPagePostButton.tsx
  frontend/src/components/MyPage/MyPagePostItem/MyPagePostItem.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/hooks/useFetch.ts
  frontend/src/mocks/data/myPagePost/myPagePostList.json
Labels: ✨ feat, ❤️ FE

#577 버튼 props 수정
  frontend/src/components/common/Button/Button.tsx
Labels: ❤️ FE, 💄 design, 🔧 fix

#581 hotfix: css 밀리는 현상 수정
  frontend/src/components/ListFilter/ListFilter.tsx
  frontend/src/components/MyPage/MyPagePostButton/MyPagePostButton.tsx
  frontend/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/layout/Header.tsx
  frontend/src/mocks/data/myPageRunnerProfile.json
  frontend/src/pages/MainPage.tsx
Labels: 🐛 bug, ❤️ FE, 💄 design

#590 CSS 깨짐 현상 (버튼 패딩, 게시물 해시태그)
  frontend/src/components/ListFilter/ListFilter.tsx
  frontend/src/components/RunnerPost/RunnerPostFilter/RunnerPostFilter.tsx
  frontend/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  frontend/src/pages/NoticePage.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/RunnerPostDetailPage.tsx
Labels: 🐛 bug, ✨ feat, ❤️ FE, 💄 design

#589 깃허브 소셜 회원 가입시 계정의 닉네임이 없을 경우 기본값으로 저장
  backend/baton/src/main/java/touch/baton/domain/member/vo/MemberName.java
  backend/baton/src/main/java/touch/baton/infra/auth/oauth/github/response/GithubMemberResponse.java
  backend/baton/src/test/java/touch/baton/domain/member/MemberTest.java
  backend/baton/src/test/java/touch/baton/domain/member/vo/MemberNameTest.java
  backend/baton/src/test/java/touch/baton/domain/member/vo/NameTest.java
Labels: 🐛 bug, 💙 BE

#592 테스트 코드 작성
  .github/workflows/frontend_ci.yml
  frontend/cypress.config.ts
  frontend/cypress/e2e/app.cy.ts
  frontend/cypress/support/commands.ts
  frontend/cypress/support/e2e.ts
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/__test__/components.test.tsx
  frontend/src/components/MyPage/MyPagePostItem/MyPagePostItem.tsx
  frontend/src/components/MyPage/MyPagePostList/MyPagePostList.tsx
  frontend/src/components/RunnerPost/RunnerPostList/RunnerPostList.tsx
  frontend/src/components/RunnerPost/RunnerPostSearchBox/RunnerPostSearchBox.tsx
  frontend/src/components/common/Toast/Toast.tsx
  frontend/src/mocks/data/runnerPostList.json
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/webpack/webpack.dev.js
Labels: ✨ feat, ❤️ FE

#575 프론트엔드 성능 최적화
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/ListFilter/ListFilter.tsx
  frontend/src/components/RunnerPost/RunnerPostFilter/RunnerPostFilter.tsx
  frontend/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/SupporterProfilePage.tsx
  frontend/src/router.tsx
  frontend/src/styles/GlobalStyles.ts
  frontend/webpack/webpack.prod.js
Labels: ✨ feat, ❤️ FE

#595 프론트엔드 메인 병합 v1.1.1
  .github/workflows/frontend_ci.yml
  frontend/cypress.config.ts
  frontend/cypress/e2e/app.cy.ts
  frontend/cypress/support/commands.ts
  frontend/cypress/support/e2e.ts
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/__test__/components.test.tsx
  frontend/src/components/ListFilter/ListFilter.tsx
  frontend/src/components/MyPage/MyPagePostButton/MyPagePostButton.tsx
  frontend/src/components/MyPage/MyPagePostItem/MyPagePostItem.tsx
  frontend/src/components/MyPage/MyPagePostList/MyPagePostList.tsx
  frontend/src/components/RunnerPost/RunnerPostFilter/RunnerPostFilter.tsx
  frontend/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  frontend/src/components/RunnerPost/RunnerPostList/RunnerPostList.tsx
  frontend/src/components/RunnerPost/RunnerPostSearchBox/RunnerPostSearchBox.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/Toast/Toast.tsx
  frontend/src/layout/Header.tsx
  frontend/src/mocks/data/myPageRunnerProfile.json
  frontend/src/mocks/data/runnerPostList.json
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/NoticePage.tsx
  frontend/src/pages/ProfileEditPage.tsx
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/src/pages/RunnerPostDetailPage.tsx
  frontend/src/pages/SupporterProfilePage.tsx
  frontend/src/router.tsx
  frontend/src/styles/GlobalStyles.ts
  frontend/webpack/webpack.dev.js
  frontend/webpack/webpack.prod.js
Labels: ❤️ FE, 🚀 deploy

#605 글 작성 후 결과 페이지 추가 및 마감기한 기본값 수정
  frontend/cypress/e2e/app.cy.ts
  frontend/src/components/MyPage/MyPagePostItem/MyPagePostItem.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/hooks/usePageRouter.ts
  frontend/src/mocks/data/myPagePost/myPagePostList.json
  frontend/src/mocks/data/supporterProfilePost.json
  frontend/src/pages/ResultPage.tsx
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/src/router.tsx
Labels: ✨ feat, ❤️ FE
