Repository woowacourse-teams/2023-baton, pull requests merged in 2024-02, with the labels that each got.

#714 사이드바 공용 컴포넌트 구현 및 랭킹 불러오는 기능 구현
  frontend/cypress/e2e/app.cy.ts
  frontend/src/apis/apis.ts
  frontend/src/assets/banner/banner.webp
  frontend/src/components/Banner/Banner.tsx
  frontend/src/components/MyPage/MyPagePostItem/MyPagePostItem.tsx
  frontend/src/components/RunnerPost/RunnerPostFilter/RunnerPostFilter.tsx
  frontend/src/components/TechLabel/TechLabel.tsx
  frontend/src/components/common/Dropdown/Dropdown.tsx
  frontend/src/components/common/Flex/Flex.tsx
  frontend/src/components/common/Label/Label.tsx
  frontend/src/components/common/SideWidget/RankerItem.tsx
  frontend/src/components/common/SideWidget/SideWidget.tsx
  frontend/src/components/common/Text/Text.tsx
  frontend/src/hooks/query/useRank.ts
  frontend/src/layout/Header.tsx
  frontend/src/layout/HomeLayout.tsx
  frontend/src/mocks/data/rank.json
  frontend/src/mocks/handlers.ts
  frontend/src/pages/LoadingPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/styles/GlobalStyles.ts
  frontend/src/styles/colorPalette.ts
  frontend/src/styles/typography.ts
  frontend/src/types/rank.ts
  frontend/tsconfig.json
Labels: ✨ feat, ❤️ FE

#719 게시글 개수 표시 기능 구현
  frontend/src/components/RunnerPost/RunnerPostFilter/RunnerPostFilter.tsx
  frontend/src/components/RunnerPost/RunnerPostItem/RunnerPostItem.tsx
  frontend/src/components/RunnerPost/RunnerPostList/RunnerPostList.tsx
  frontend/src/components/TechLabel/TechLabel.tsx
  frontend/src/components/common/SideWidget/RankerItem.tsx
  frontend/src/components/common/SideWidget/SideWidget.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/query/useTotalCount.ts
  frontend/src/hooks/useViewport.ts
  frontend/src/mocks/data/rank.json
  frontend/src/mocks/data/runnerPostList.json
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/NoticePage.tsx
  frontend/src/types/runnerPost.ts
Labels: ✨ feat, ❤️ FE, ♻️ refactor, 🔧 fix

#722 reviewCount가 0인 항목이 조회가 되면 제외되도록 구현
  backend/baton/src/main/java/touch/baton/domain/member/query/repository/RankQuerydslRepository.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/query/repository/RunnerPostPageRepository.java
  backend/baton/src/test/java/touch/baton/domain/member/query/repository/RankQuerydslRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/member/query/service/RankQueryServiceTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/query/service/RunnerPostQueryServiceTest.java
Labels: 💙 BE, ♻️ refactor

#726 게시물 개수 표시 기능 수정
  frontend/src/apis/apis.ts
  frontend/src/components/RunnerPost/RunnerPostFilter/RunnerPostFilter.tsx
  frontend/src/hooks/query/usePostCount.ts
  frontend/src/hooks/query/useTotalCount.ts
  frontend/src/layout/MyMenu.tsx
  frontend/src/mocks/data/postCount.json
  frontend/src/mocks/data/runnerPostList.json
  frontend/src/mocks/handlers.ts
  frontend/src/types/runnerPost.ts
Labels: ✨ feat, ❤️ FE, ♻️ refactor

#730 게시물 개수 api 타입 수정
  frontend/cypress/e2e/app.cy.ts
  frontend/src/apis/apis.ts
  frontend/src/components/RunnerPost/RunnerPostFilter/RunnerPostFilter.tsx
  frontend/src/hooks/query/usePostCount.ts
  frontend/src/mocks/data/postCount.json
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/RunnerPostCreatePage.tsx
  frontend/src/types/runnerPost.ts
Labels: ❤️ FE, ♻️ refactor

#728 리뷰 상태별로 게시글 전체 개수를 조회하는 기능 구현
  backend/baton/src/docs/asciidoc/RunnerPostReadApi.adoc
  backend/baton/src/main/java/touch/baton/domain/runnerpost/query/controller/RunnerPostQueryController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/query/controller/response/RunnerPostResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/query/repository/RunnerPostQueryRepository.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/query/service/RunnerPostQueryService.java
  backend/baton/src/test/java/touch/baton/assure/common/AssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/repository/TestRunnerPostCommandRepository.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostSteps.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/query/count/RunnerPostStatusCountAssruedTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/support/query/count/RunnerPostStatusCountAssuredSupport.java
  backend/baton/src/test/java/touch/baton/config/AssuredTestConfig.java
  backend/baton/src/test/java/touch/baton/config/RepositoryTestConfig.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostStatusCountApiTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/query/repository/RunnerPostQueryRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/query/service/RunnerPostQueryServiceTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerPostFixture.java
Labels: ✨ feat, 💙 BE

#731 백엔드 배포 작업
  backend/baton/src/docs/asciidoc/RunnerPostReadApi.adoc
  backend/baton/src/main/java/touch/baton/domain/runnerpost/query/controller/RunnerPostQueryController.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/query/controller/response/RunnerPostResponse.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/query/repository/RunnerPostQueryRepository.java
  backend/baton/src/main/java/touch/baton/domain/runnerpost/query/service/RunnerPostQueryService.java
  backend/baton/src/test/java/touch/baton/assure/common/AssuredSupport.java
  backend/baton/src/test/java/touch/baton/assure/repository/TestRunnerPostCommandRepository.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostSteps.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/query/count/RunnerPostStatusCountAssruedTest.java
  backend/baton/src/test/java/touch/baton/assure/runnerpost/support/query/count/RunnerPostStatusCountAssuredSupport.java
  backend/baton/src/test/java/touch/baton/config/AssuredTestConfig.java
  backend/baton/src/test/java/touch/baton/config/RepositoryTestConfig.java
  backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostStatusCountApiTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/query/repository/RunnerPostQueryRepositoryTest.java
  backend/baton/src/test/java/touch/baton/domain/runnerpost/query/service/RunnerPostQueryServiceTest.java
  backend/baton/src/test/java/touch/baton/fixture/domain/RunnerPostFixture.java
Labels: 💙 BE, 🚀 deploy

#733 프론트엔드 빌드 속도 개선 및 번들 사이즈 최적화
  frontend/.babelrc
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack/webpack.common.js
  frontend/webpack/webpack.prod.js
Labels: ❤️ FE, ♻️ refactor
